"""Regression tests for issue #778: Alembic must run with `render_as_batch=True`.

ADR-024 Consequences (`docs/adr/024-database-quickstart-sqlite-tiered.md:87`)
requires `render_as_batch=True` on both `context.configure(...)` call sites in
`alembic/env.py` (`run_migrations_offline` and `do_run_migrations`), because
SQLite's limited `ALTER TABLE` support means autogenerated migrations must be
wrapped in `with op.batch_alter_table(...)`.

Rather than grepping `env.py`'s source text, these tests execute the real
`alembic/env.py` file exactly as the `alembic` CLI would (via
`alembic.command.upgrade`, which internally calls `ScriptDirectory.run_env()`)
for both the offline (`--sql`) and online code paths, and record the actual
keyword arguments alembic's `MigrationContext` received. This proves the
running configuration, not just the source text.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
from alembic import command, context
from alembic.config import Config
from alembic.runtime.migration import MigrationContext

from app.core.config import get_settings
from app.db.session import get_engine

_BACKEND_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def _alembic_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Config:
    """Build a real Alembic `Config` pointed at an isolated SQLite database.

    Args:
        tmp_path: pytest's per-test temporary directory fixture.
        monkeypatch: pytest's monkeypatch fixture, auto-reverted per test.

    Returns:
        A `Config` wired to the project's real `alembic/env.py` and an
        on-disk SQLite database unique to this test.
    """
    monkeypatch.setenv("ENVIRONMENT", "test")
    monkeypatch.setenv("ALLOWED_ORIGINS", "http://localhost:5173")
    monkeypatch.setenv("DATABASE_URL", f"sqlite+aiosqlite:///{tmp_path}/alembic_probe.db")
    get_settings.cache_clear()
    get_engine.cache_clear()

    config = Config(str(_BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(_BACKEND_ROOT / "alembic"))
    return config


def _spy_on_configure(
    monkeypatch: pytest.MonkeyPatch,
) -> list[dict[str, Any]]:
    """Wrap the real `alembic.context.configure` to record its kwargs.

    The wrapper still calls through to the original implementation so
    `env.py`'s migration run completes normally; only the observed kwargs are
    captured for assertions.

    Args:
        monkeypatch: pytest's monkeypatch fixture, auto-reverted per test.

    Returns:
        A list that the wrapper appends one kwargs dict to per call.
    """
    calls: list[dict[str, Any]] = []
    original_configure = context.configure

    def _spy(**kwargs: Any) -> MigrationContext:
        calls.append(kwargs)
        return original_configure(**kwargs)

    monkeypatch.setattr(context, "configure", _spy)
    return calls


class TestAlembicRendersAsBatch:
    """Issue #778: both `env.py` configure call sites must set `render_as_batch=True`."""

    def test_offline_mode_configures_render_as_batch(
        self, _alembic_config: Config, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = _spy_on_configure(monkeypatch)

        command.upgrade(_alembic_config, "head", sql=True)

        assert len(calls) == 1
        assert calls[0].get("render_as_batch") is True

    def test_online_mode_configures_render_as_batch(
        self, _alembic_config: Config, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = _spy_on_configure(monkeypatch)

        command.upgrade(_alembic_config, "head")

        assert len(calls) == 1
        assert calls[0].get("render_as_batch") is True
