// 本檔為 generated view——請勿手動編輯
// Generated by NoteCraft @ai-visualize (content-visualize skill); regenerate from the marker in specs/annotation/015-annotation-workspace/diagrams.mdx.

import { useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type ReactNode } from 'react';
import { KeyRound, Sparkles, Database, Lock, Ban, TriangleAlert, GripVertical } from 'lucide-react';
import clsx from 'clsx';

// ---------------------------------------------------------------------------
// SCOPED_CSS —— NoteCraft 的 Tailwind JIT 掃描不到 .notecraft/components/ 下的
// class（見 review-unit-state-machine-interactive.tsx 的先例），故本檔自帶
// 用到的 utility，全部限定在 .awerd-root 底下，不依賴宿主 CSS。SVG 內部一律
// 用行內屬性（fill/stroke/font-size）著色，不吃這份 CSS。
// ---------------------------------------------------------------------------

const SCOPED_CSS = `
.awerd-root { font-size: 0.875rem; line-height: 1.5; color: #334155; }
.awerd-root p { margin: 0; }
.awerd-root button { font: inherit; color: inherit; background: none; border: 0; }

.awerd-root .flex { display: flex; }
.awerd-root .items-center { align-items: center; }
.awerd-root .justify-between { justify-content: space-between; }
.awerd-root .flex-wrap { flex-wrap: wrap; }
.awerd-root .gap-1 { gap: 0.25rem; }
.awerd-root .gap-2 { gap: 0.5rem; }
.awerd-root .gap-3 { gap: 0.75rem; }
.awerd-root .gap-4 { gap: 1rem; }
.awerd-root .space-y-4 > * + * { margin-top: 1rem; }

.awerd-root .rounded { border-radius: 4px; }
.awerd-root .rounded-lg { border-radius: 8px; }
.awerd-root .border { border-width: 1px; border-style: solid; border-color: #E2E8F0; }
.awerd-root .border-indigo-500 { border-color: #6366F1; }
.awerd-root .bg-white { background-color: #FFFFFF; }
.awerd-root .bg-indigo-50 { background-color: #EEF2FF; }

.awerd-root .px-2 { padding-left: 0.5rem; padding-right: 0.5rem; }
.awerd-root .px-3 { padding-left: 0.75rem; padding-right: 0.75rem; }
.awerd-root .py-1 { padding-top: 0.25rem; padding-bottom: 0.25rem; }
.awerd-root .py-1\\.5 { padding-top: 0.375rem; padding-bottom: 0.375rem; }

.awerd-root .text-xs { font-size: 0.75rem; line-height: 1rem; }
.awerd-root .text-sm { font-size: 0.875rem; line-height: 1.25rem; }
.awerd-root .font-medium { font-weight: 500; }
.awerd-root .font-semibold { font-weight: 600; }
.awerd-root .text-slate-500 { color: #64748B; }
.awerd-root .text-slate-600 { color: #475569; }
.awerd-root .text-indigo-600 { color: #4F46E5; }

.awerd-root .transition-colors { transition: color 160ms ease-out, background-color 160ms ease-out, border-color 160ms ease-out; }
.awerd-root [role="switch"] { cursor: pointer; }
.awerd-root .awerd-relation-fade { transition: opacity 160ms ease-out; }
.awerd-root .awerd-border-fade { transition: stroke 160ms ease-out, stroke-width 160ms ease-out; }
@media (prefers-reduced-motion: reduce) {
  .awerd-root .transition-colors,
  .awerd-root .awerd-relation-fade,
  .awerd-root .awerd-border-fade {
    transition: none;
  }
}
`;

// ---------------------------------------------------------------------------
// 型別 —— 對齊 spec.md〈關鍵實體〉與 diagrams.mdx 標記 prompt 的欄位描述
// ---------------------------------------------------------------------------

type FieldKind = 'stored' | 'derived' | 'key' | 'derived-key';

interface FieldSpec {
  name: string;
  typeLabel: string;
  kind: FieldKind;
  note?: string;
}

type TableId =
  | 'taskProfile'
  | 'annotationListItem'
  | 'annotationRecord'
  | 'outputAnswer'
  | 'reviewUnit'
  | 'reviewDecision'
  | 'disputeItem'
  | 'annotationHistoryItem'
  | 'guidelineAsset'
  | 'adjudicationItem'
  | 'goldRecord';

interface TableSpec {
  id: TableId;
  title: string;
  subtitle?: string;
  subtitleTone?: 'muted' | 'amber';
  keyLabel?: string;
  deprecated?: boolean;
  fields: FieldSpec[];
  x: number;
  y: number;
  width: number;
}

type Side = 'left' | 'right' | 'top' | 'bottom';
type MarkerKind = 'one' | 'many' | 'zero-one' | 'open-arrow' | 'circle';
type MarkerColorKey = 'default' | 'mutedDefault' | 'accent' | 'dim';

interface RelationSpec {
  id: string;
  from: TableId;
  fromField?: string;
  to: TableId;
  toField?: string;
  derived: boolean;
  label: string[];
  startMarker?: MarkerKind;
  endMarker?: MarkerKind;
  avoidCards?: boolean;
}

// ---------------------------------------------------------------------------
// 設計 token（label-suite-design）
// ---------------------------------------------------------------------------

const PAPER = '#F5F3FF';
const INK = '#1E1B4B';
const MUTED = '#64748B';
const ACCENT = '#6366F1';
const CARD_BG = '#FFFFFF';
const CARD_BORDER = '#E2E8F0';
const HEADER_BG = '#EEF2FF';
const HEADER_TEXT = '#4338CA';
const STORED_TEXT = '#334155';
const DIM_TEXT = '#CBD5E1';
const KEY_DIM_TEXT = '#94A3B8';
const DEPRECATED_BORDER = '#CBD5E1';
const DEPRECATED_BG = '#F8FAFC';
const DEPRECATED_TEXT = '#94A3B8';
const AMBER_TEXT = '#B45309';
const SANS = 'Inter, "Noto Sans TC", sans-serif';
const MONO = '"JetBrains Mono", ui-monospace, Menlo, monospace';

const MARKER_COLORS: Record<MarkerColorKey, string> = {
  default: '#475569',
  mutedDefault: '#94A3B8',
  accent: ACCENT,
  dim: '#CBD5E1',
};

// ---------------------------------------------------------------------------
// 版面常數
// ---------------------------------------------------------------------------

const HEADER_TITLE_HEIGHT = 32;
const SUBTITLE_HEIGHT = 16;
const KEYLABEL_HEIGHT = 16;
const ROW_HEIGHT = 22;
const TYPE_OWN_LINE_HEIGHT = 13;
const NOTE_LINE_HEIGHT = 13;
const BOTTOM_PADDING = 10;
const TYPE_INLINE_MAX = 12;
const VIEW_WIDTH = 1760;
const VIEW_HEIGHT = 760;

// ---------------------------------------------------------------------------
// 資料——11 張表，欄位逐字對齊 diagrams.mdx 標記 prompt（來源核對：spec.md〈關鍵實體〉）
// ---------------------------------------------------------------------------

const TABLES: TableSpec[] = [
  {
    id: 'taskProfile',
    title: 'TaskProfile',
    subtitle: '唯讀（上游 013 凍結）',
    x: 40,
    y: 60,
    width: 280,
    fields: [
      { name: 'task_id', typeLabel: '', kind: 'key' },
      { name: 'input_type', typeLabel: '', kind: 'stored' },
      { name: 'outputs[]', typeLabel: 'OutputConfig[]（type, config）', kind: 'stored' },
      { name: 'field_role_map', typeLabel: '', kind: 'stored' },
      { name: 'item_pair_labels?', typeLabel: '', kind: 'stored' },
      { name: 'guidelineFiles?', typeLabel: '{name,type,url}[]', kind: 'stored' },
      { name: 'materializedRuns?', typeLabel: '', kind: 'stored' },
      { name: 'forceShowGuideline?', typeLabel: '', kind: 'stored' },
      { name: 'guidelineVersion?', typeLabel: '', kind: 'stored' },
    ],
  },
  {
    id: 'guidelineAsset',
    title: 'GuidelineAsset',
    x: 40,
    y: 360,
    width: 280,
    fields: [
      { name: '文字摘要', typeLabel: '', kind: 'stored' },
      { name: '檔案清單', typeLabel: '', kind: 'stored', note: '來源 TaskProfile.guidelineFiles' },
      { name: 'modal／右欄同步呈現設定', typeLabel: '', kind: 'stored' },
      { name: '指引閘門確認紀錄', typeLabel: '', kind: 'stored', note: '逐 task_id' },
    ],
  },
  {
    id: 'annotationListItem',
    title: 'AnnotationListItem',
    subtitle: '由 task-detail run 發布事件建立',
    x: 380,
    y: 60,
    width: 280,
    fields: [
      { name: 'task_id', typeLabel: '', kind: 'key' },
      { name: 'sample_id', typeLabel: '', kind: 'key' },
      { name: 'run_type', typeLabel: '', kind: 'stored' },
      { name: 'trial_round?', typeLabel: '', kind: 'stored' },
      { name: 'sample_snapshot_id', typeLabel: '', kind: 'stored' },
      { name: '完成狀態', typeLabel: '', kind: 'stored' },
      { name: '鎖定狀態', typeLabel: '', kind: 'stored' },
      { name: '摘要資訊', typeLabel: '', kind: 'stored' },
    ],
  },
  {
    id: 'annotationHistoryItem',
    title: 'AnnotationHistoryItem',
    subtitle: '關聯鍵未定義',
    subtitleTone: 'amber',
    x: 380,
    y: 340,
    width: 280,
    fields: [
      { name: 'action', typeLabel: 'HISTORY_ACTIONS 九值', kind: 'stored' },
      { name: 'role', typeLabel: '', kind: 'stored' },
      { name: 'actor_id', typeLabel: '', kind: 'stored' },
      { name: 'at', typeLabel: '', kind: 'stored' },
      { name: 'summary', typeLabel: '', kind: 'stored' },
      { name: 'result_snapshot', typeLabel: '', kind: 'stored' },
      { name: 'started_at', typeLabel: '', kind: 'stored' },
      { name: 'lead_time', typeLabel: '', kind: 'stored' },
      { name: 'reason', typeLabel: '', kind: 'stored' },
    ],
  },
  {
    id: 'annotationRecord',
    title: 'AnnotationRecord',
    x: 720,
    y: 60,
    width: 280,
    fields: [
      { name: 'sample_id', typeLabel: '', kind: 'key' },
      { name: 'answers', typeLabel: 'OutputAnswer[]', kind: 'stored' },
      { name: 'note?', typeLabel: '', kind: 'stored' },
      { name: 'version', typeLabel: '', kind: 'stored' },
      { name: 'status', typeLabel: 'pending | saved | submitted', kind: 'stored' },
      { name: 'annotator_id', typeLabel: '', kind: 'key' },
      { name: 'submitted_at?', typeLabel: '', kind: 'stored' },
    ],
  },
  {
    id: 'outputAnswer',
    title: 'OutputAnswer',
    subtitle: '內嵌於 AnnotationRecord.answers[]',
    x: 720,
    y: 320,
    width: 280,
    fields: [
      { name: 'type', typeLabel: 'OUTPUT_TYPE_KEYS', kind: 'key' },
      { name: 'bypass', typeLabel: 'boolean', kind: 'stored' },
      { name: 'note?', typeLabel: '', kind: 'stored' },
      { name: 'version', typeLabel: '', kind: 'stored' },
      {
        name: 'payload（依 type）',
        typeLabel: '',
        kind: 'stored',
        note: '8 種形狀：single_label … free_text',
      },
    ],
  },
  {
    id: 'reviewUnit',
    title: 'ReviewUnit',
    keyLabel: '定址 = sample_id × annotator_id × run_type',
    x: 1060,
    y: 60,
    width: 280,
    fields: [
      { name: 'sample_id', typeLabel: '', kind: 'key' },
      { name: 'annotator_id', typeLabel: '', kind: 'key' },
      { name: 'run_type', typeLabel: '', kind: 'key' },
      { name: 'status', typeLabel: 'pending | disputed | finalized', kind: 'derived', note: '推導' },
      { name: 'reviewer_decisions[]', typeLabel: '', kind: 'stored', note: 'v5.0.0：至多一筆' },
      { name: 'diffs_by_output_type', typeLabel: '', kind: 'derived', note: '推導，FR-052' },
    ],
  },
  {
    id: 'adjudicationItem',
    title: 'AdjudicationItem',
    subtitle: '已廢止 v4.0.0，名稱保留不重用',
    deprecated: true,
    x: 1060,
    y: 380,
    width: 280,
    fields: [],
  },
  {
    id: 'goldRecord',
    title: 'GoldRecord',
    subtitle: '已廢止 v4.0.0，名稱保留不重用',
    deprecated: true,
    x: 1060,
    y: 470,
    width: 280,
    fields: [],
  },
  {
    id: 'reviewDecision',
    title: 'ReviewDecision',
    keyLabel: '維度 = 標記員 × 輸出類型',
    x: 1400,
    y: 60,
    width: 280,
    fields: [
      { name: 'annotator_id', typeLabel: '', kind: 'key' },
      { name: 'output_type', typeLabel: '', kind: 'key' },
      { name: 'decision', typeLabel: 'approve | modify | bypass', kind: 'stored' },
      { name: 'correction?', typeLabel: '', kind: 'stored' },
      { name: 'reason?', typeLabel: '', kind: 'stored', note: 'decision = modify|bypass 時必填' },
      { name: 'reviewer_id', typeLabel: '', kind: 'stored' },
      { name: 'decided_at', typeLabel: '', kind: 'stored' },
    ],
  },
  {
    id: 'disputeItem',
    title: 'DisputeItem',
    subtitle: 'votes[] 與 finalized_* 是僅有的寫入狀態',
    x: 1400,
    y: 320,
    width: 310,
    fields: [
      { name: 'output_type', typeLabel: '', kind: 'derived-key', note: '推導（FR-052）' },
      { name: 'item_key', typeLabel: '', kind: 'derived-key', note: '推導（FR-052）' },
      { name: 'annotator_value?', typeLabel: '', kind: 'derived', note: '推導（FR-052）' },
      { name: 'reviewer_values', typeLabel: '', kind: 'derived', note: '推導（FR-052）；至多一筆' },
      { name: 'votes[]?', typeLabel: 'arbiter_id、choice：adopt_a|adopt_b|reject、voted_at', kind: 'stored' },
      { name: 'finalized_value?', typeLabel: '', kind: 'stored' },
      { name: 'finalized_by?', typeLabel: '', kind: 'stored' },
    ],
  },
];

const TABLE_MAP: Record<TableId, TableSpec> = TABLES.reduce(
  (acc, table) => {
    acc[table.id] = table;
    return acc;
  },
  {} as Record<TableId, TableSpec>
);

const RELATIONS: RelationSpec[] = [
  {
    id: 'r1',
    from: 'taskProfile',
    fromField: 'task_id',
    to: 'annotationListItem',
    toField: 'task_id',
    derived: false,
    label: ['task_id'],
    startMarker: 'one',
    endMarker: 'many',
  },
  {
    id: 'r2',
    from: 'annotationRecord',
    fromField: 'answers',
    to: 'outputAnswer',
    derived: false,
    label: ['answers[]（內嵌，依 outputs[] 順序）'],
    startMarker: 'one',
    endMarker: 'many',
  },
  {
    id: 'r3',
    from: 'taskProfile',
    fromField: 'outputs[]',
    to: 'outputAnswer',
    toField: 'type',
    derived: false,
    label: ['型別約束（非基數）'],
    endMarker: 'open-arrow',
    avoidCards: true,
  },
  {
    id: 'r4',
    from: 'annotationRecord',
    to: 'reviewUnit',
    derived: true,
    label: ['sample_id + annotator_id', '（AnnotationRecord 無 run_type，推導）'],
    startMarker: 'circle',
    endMarker: 'circle',
  },
  {
    id: 'r5',
    from: 'reviewUnit',
    fromField: 'reviewer_decisions[]',
    to: 'reviewDecision',
    derived: false,
    label: ['reviewer_decisions[]（至多一筆）'],
    startMarker: 'one',
    endMarker: 'zero-one',
  },
  {
    id: 'r6',
    from: 'reviewUnit',
    to: 'disputeItem',
    derived: true,
    label: ['推導（FR-052；僅 votes/finalized 寫入）'],
    startMarker: 'circle',
    endMarker: 'circle',
  },
  {
    id: 'r7',
    from: 'taskProfile',
    fromField: 'guidelineFiles?',
    to: 'guidelineAsset',
    derived: false,
    label: ['guidelineFiles → 來源'],
    startMarker: 'one',
    endMarker: 'one',
  },
  {
    id: 'r8',
    from: 'annotationListItem',
    to: 'annotationRecord',
    derived: true,
    label: ['task_id / sample_id', '（AnnotationRecord 無 task_id，推導）'],
    startMarker: 'circle',
    endMarker: 'circle',
  },
];

// ---------------------------------------------------------------------------
// 版面計算——沿用一組純函式，供繪製與錨點計算共用
// ---------------------------------------------------------------------------

interface FieldLayout {
  field: FieldSpec;
  top: number;
  height: number;
  center: number;
  typeOwnLine: boolean;
}

interface TableLayout {
  headerHeight: number;
  rows: FieldLayout[];
  totalHeight: number;
}

function computeTableLayout(table: TableSpec): TableLayout {
  const headerHeight = HEADER_TITLE_HEIGHT + (table.subtitle ? SUBTITLE_HEIGHT : 0) + (table.keyLabel ? KEYLABEL_HEIGHT : 0);
  let cursor = headerHeight;
  const rows: FieldLayout[] = table.fields.map((field) => {
    const typeOwnLine = field.typeLabel.length > TYPE_INLINE_MAX;
    let height = ROW_HEIGHT;
    if (typeOwnLine) height += TYPE_OWN_LINE_HEIGHT;
    if (field.note) height += NOTE_LINE_HEIGHT;
    const top = cursor;
    cursor += height;
    return { field, top, height, center: top + ROW_HEIGHT / 2, typeOwnLine };
  });
  return { headerHeight, rows, totalHeight: cursor + BOTTOM_PADDING };
}

const TABLE_LAYOUTS: Record<TableId, TableLayout> = TABLES.reduce(
  (acc, table) => {
    acc[table.id] = computeTableLayout(table);
    return acc;
  },
  {} as Record<TableId, TableLayout>
);

type PositionMap = Record<TableId, { x: number; y: number }>;

const INITIAL_POSITIONS: PositionMap = TABLES.reduce((acc, table) => {
  acc[table.id] = { x: table.x, y: table.y };
  return acc;
}, {} as PositionMap);

function getTableCenter(tableId: TableId, positions: PositionMap): { cx: number; cy: number } {
  const table = TABLE_MAP[tableId];
  const pos = positions[tableId];
  const layout = TABLE_LAYOUTS[tableId];
  return { cx: pos.x + table.width / 2, cy: pos.y + layout.totalHeight / 2 };
}

function getFieldAnchor(tableId: TableId, fieldName: string | undefined, side: Side, positions: PositionMap): { x: number; y: number } {
  const table = TABLE_MAP[tableId];
  const pos = positions[tableId];
  const layout = TABLE_LAYOUTS[tableId];
  if (side === 'top') return { x: pos.x + table.width / 2, y: pos.y };
  if (side === 'bottom') return { x: pos.x + table.width / 2, y: pos.y + layout.totalHeight };
  const row = fieldName ? layout.rows.find((r) => r.field.name === fieldName) : undefined;
  const y = pos.y + (row ? row.center : layout.totalHeight / 2);
  return { x: side === 'left' ? pos.x : pos.x + table.width, y };
}

function pickSides(fromCenter: { cx: number; cy: number }, toCenter: { cx: number; cy: number }): { fromSide: Side; toSide: Side } {
  const dx = toCenter.cx - fromCenter.cx;
  const dy = toCenter.cy - fromCenter.cy;
  if (Math.abs(dx) < 40) {
    return dy >= 0 ? { fromSide: 'bottom', toSide: 'top' } : { fromSide: 'top', toSide: 'bottom' };
  }
  return dx >= 0 ? { fromSide: 'right', toSide: 'left' } : { fromSide: 'left', toSide: 'right' };
}

function buildConnectorPath(
  x1: number,
  y1: number,
  x2: number,
  y2: number
): { d: string; midX: number; midY: number } {
  const dx = x2 - x1;
  if (Math.abs(dx) < 40) {
    const midY = (y1 + y2) / 2;
    return { d: `M ${x1} ${y1} C ${x1} ${midY}, ${x2} ${midY}, ${x2} ${y2}`, midX: (x1 + x2) / 2, midY };
  }
  const offset = Math.max(60, Math.abs(dx) * 0.35);
  const c1x = x1 + offset;
  const c1y = y1;
  const c2x = x2 - offset;
  const c2y = y2;
  return {
    d: `M ${x1} ${y1} C ${c1x} ${c1y}, ${c2x} ${c2y}, ${x2} ${y2}`,
    midX: (x1 + x2) / 2,
    midY: (y1 + y2) / 2,
  };
}

// R3 crosses the AnnotationListItem / AnnotationHistoryItem column, so it runs through the gap between them.
function buildCorridorPath(
  start: { x: number; y: number },
  end: { x: number; y: number },
  positions: PositionMap
): { d: string; midX: number; midY: number } {
  const upper = positions.annotationListItem;
  const lower = positions.annotationHistoryItem;
  const corridorY = (upper.y + TABLE_LAYOUTS.annotationListItem.totalHeight + lower.y) / 2;
  const leftGapX = (start.x + upper.x) / 2;
  const rightGapX = (upper.x + TABLE_MAP.annotationListItem.width + end.x) / 2;
  return {
    d: `M ${start.x} ${start.y} H ${leftGapX} V ${corridorY} H ${rightGapX} V ${end.y} H ${end.x}`,
    midX: (leftGapX + rightGapX) / 2,
    midY: corridorY,
  };
}

function estimateLabelWidth(lines: string[]): number {
  let maxW = 0;
  for (const line of lines) {
    let w = 0;
    for (const ch of line) {
      w += /[　-鿿＀-￯]/.test(ch) ? 9.2 : 5.2;
    }
    maxW = Math.max(maxW, w);
  }
  return maxW + 16;
}

// ---------------------------------------------------------------------------
// Markers——每種基數符號各三個色階（default / mutedDefault / accent / dim）
// ---------------------------------------------------------------------------

function renderMarkers(): ReactNode {
  const states: MarkerColorKey[] = ['default', 'mutedDefault', 'accent', 'dim'];
  return states.flatMap((state) => {
    const color = MARKER_COLORS[state];
    return [
      <marker key={`one-${state}`} id={`awerd-one-${state}`} markerWidth="12" markerHeight="14" refX="10" refY="7" orient="auto-start-reverse">
        <line x1="5" y1="1" x2="5" y2="13" stroke={color} strokeWidth="1.3" />
        <line x1="9" y1="1" x2="9" y2="13" stroke={color} strokeWidth="1.3" />
      </marker>,
      <marker key={`many-${state}`} id={`awerd-many-${state}`} markerWidth="14" markerHeight="14" refX="12" refY="7" orient="auto-start-reverse">
        <path d="M 0 7 L 12 1 M 0 7 L 12 7 M 0 7 L 12 13" fill="none" stroke={color} strokeWidth="1.3" />
      </marker>,
      <marker key={`zero-one-${state}`} id={`awerd-zero-one-${state}`} markerWidth="18" markerHeight="14" refX="16" refY="7" orient="auto-start-reverse">
        <circle cx="5" cy="7" r="4" fill={PAPER} stroke={color} strokeWidth="1.2" />
        <line x1="13" y1="1" x2="13" y2="13" stroke={color} strokeWidth="1.3" />
      </marker>,
      <marker key={`open-arrow-${state}`} id={`awerd-open-arrow-${state}`} markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto-start-reverse">
        <path d="M 1 1 L 10 6 L 1 11" fill="none" stroke={color} strokeWidth="1.4" />
      </marker>,
      <marker key={`circle-${state}`} id={`awerd-circle-${state}`} markerWidth="12" markerHeight="12" refX="6" refY="6" orient="auto-start-reverse">
        <circle cx="6" cy="6" r="4" fill={PAPER} stroke={color} strokeWidth="1.2" />
      </marker>,
    ];
  });
}

// ---------------------------------------------------------------------------
// 子元件
// ---------------------------------------------------------------------------

interface HoverField {
  table: TableId;
  field: string;
}

function RelationLine({
  rel,
  positions,
  hoveredTable,
  hoveredField,
  emphasizeDerived,
}: {
  rel: RelationSpec;
  positions: PositionMap;
  hoveredTable: TableId | null;
  hoveredField: HoverField | null;
  emphasizeDerived: boolean;
}) {
  const fromCenter = getTableCenter(rel.from, positions);
  const toCenter = getTableCenter(rel.to, positions);
  const { fromSide, toSide } = pickSides(fromCenter, toCenter);
  const start = getFieldAnchor(rel.from, rel.fromField, fromSide, positions);
  const end = getFieldAnchor(rel.to, rel.toField, toSide, positions);
  const { d, midX, midY } = rel.avoidCards ? buildCorridorPath(start, end, positions) : buildConnectorPath(start.x, start.y, end.x, end.y);

  const anyHoverActive = hoveredTable !== null || hoveredField !== null;
  let isActive = true;
  if (hoveredField) {
    const matchesFrom = rel.from === hoveredField.table && rel.fromField === hoveredField.field;
    const matchesTo = rel.to === hoveredField.table && rel.toField === hoveredField.field;
    isActive = matchesFrom || matchesTo;
  } else if (hoveredTable) {
    isActive = rel.from === hoveredTable || rel.to === hoveredTable;
  }

  const colorKey: MarkerColorKey = emphasizeDerived ? (rel.derived ? 'accent' : 'dim') : rel.derived ? 'mutedDefault' : 'default';
  const stroke = MARKER_COLORS[colorKey];
  const opacity = anyHoverActive ? (isActive ? 1 : 0.25) : 1;
  const strokeWidth = anyHoverActive && isActive ? 2.4 : rel.derived ? 1.3 : 1.5;
  const dash = rel.derived ? '5,4' : undefined;
  const labelWidth = estimateLabelWidth(rel.label);
  const labelHeight = rel.label.length * 12 + 8;

  return (
    <g className="awerd-relation-fade" opacity={opacity}>
      <path d={d} fill="none" stroke="transparent" strokeWidth={16} />
      <path
        d={d}
        fill="none"
        stroke={stroke}
        strokeWidth={strokeWidth}
        strokeDasharray={dash}
        markerStart={rel.startMarker ? `url(#awerd-${rel.startMarker}-${colorKey})` : undefined}
        markerEnd={rel.endMarker ? `url(#awerd-${rel.endMarker}-${colorKey})` : undefined}
      />
      <rect x={midX - labelWidth / 2} y={midY - labelHeight / 2} width={labelWidth} height={labelHeight} rx={4} fill={PAPER} />
      {rel.label.map((line, index) => (
        <text
          key={line}
          x={midX}
          y={midY - labelHeight / 2 + 12 * (index + 1) - 2}
          textAnchor="middle"
          fontSize="9"
          fontFamily={MONO}
          fill={isActive || !anyHoverActive ? stroke : '#94A3B8'}
        >
          {line}
        </text>
      ))}
    </g>
  );
}

function fieldColor(kind: FieldKind, emphasizeDerived: boolean): { text: string; weight: string; italic: boolean } {
  const isDerived = kind === 'derived' || kind === 'derived-key';
  if (emphasizeDerived) {
    if (isDerived) return { text: ACCENT, weight: '700', italic: false };
    return { text: kind === 'key' ? KEY_DIM_TEXT : DIM_TEXT, weight: '500', italic: false };
  }
  if (kind === 'key' || kind === 'derived-key') return { text: INK, weight: '600', italic: kind === 'derived-key' };
  if (kind === 'derived') return { text: MUTED, weight: '500', italic: true };
  return { text: STORED_TEXT, weight: '500', italic: false };
}

function TableCard({
  table,
  position,
  hovered,
  hoveredField,
  highlightedFieldKeys,
  highlightedWholeTables,
  emphasizeDerived,
  onHoverTable,
  onLeaveTable,
  onHoverField,
  onLeaveField,
  onPointerDownHeader,
  onPointerMoveHeader,
  onPointerUpHeader,
  dragging,
}: {
  table: TableSpec;
  position: { x: number; y: number };
  hovered: boolean;
  hoveredField: HoverField | null;
  highlightedFieldKeys: Set<string>;
  highlightedWholeTables: Set<TableId>;
  emphasizeDerived: boolean;
  onHoverTable: () => void;
  onLeaveTable: () => void;
  onHoverField: (fieldName: string) => void;
  onLeaveField: () => void;
  onPointerDownHeader: (event: ReactPointerEvent<SVGRectElement>) => void;
  onPointerMoveHeader: (event: ReactPointerEvent<SVGRectElement>) => void;
  onPointerUpHeader: (event: ReactPointerEvent<SVGRectElement>) => void;
  dragging: boolean;
}) {
  const layout = TABLE_LAYOUTS[table.id];
  const isWholeHighlighted = hovered || highlightedWholeTables.has(table.id);
  const borderColor = table.deprecated ? DEPRECATED_BORDER : isWholeHighlighted ? ACCENT : CARD_BORDER;
  const borderWidth = isWholeHighlighted && !table.deprecated ? 2 : 1;
  const clipId = `awerd-clip-${table.id}`;

  return (
    <g
      opacity={table.deprecated ? 0.6 : 1}
      onMouseEnter={onHoverTable}
      onMouseLeave={onLeaveTable}
      aria-label={`實體：${table.title}`}
    >
      <clipPath id={clipId}>
        <rect x={position.x} y={position.y} width={table.width} height={layout.totalHeight} rx={12} />
      </clipPath>
      <g clipPath={`url(#${clipId})`}>
        <rect x={position.x} y={position.y} width={table.width} height={layout.totalHeight} fill={table.deprecated ? DEPRECATED_BG : CARD_BG} />
        <rect
          x={position.x}
          y={position.y}
          width={table.width}
          height={layout.headerHeight}
          fill={table.deprecated ? DEPRECATED_BG : HEADER_BG}
        />
      </g>
      <rect
        x={position.x}
        y={position.y}
        width={table.width}
        height={layout.totalHeight}
        rx={12}
        fill="none"
        stroke={borderColor}
        strokeWidth={borderWidth}
        className="awerd-border-fade"
      />

      {/* 表頭文字（不可互動，避免蓋住下方拖曳把手） */}
      <g style={{ pointerEvents: 'none' }}>
        {table.deprecated && <Ban x={position.x + 12} y={position.y + 9} size={13} color={DEPRECATED_TEXT} />}
        {!table.deprecated && table.id === 'taskProfile' && <Lock x={position.x + table.width - 24} y={position.y + 9} size={13} color={HEADER_TEXT} />}
        <text
          x={position.x + (table.deprecated ? 31 : 14)}
          y={position.y + 21}
          fontSize="12"
          fontWeight="600"
          fill={table.deprecated ? DEPRECATED_TEXT : HEADER_TEXT}
          fontFamily={SANS}
        >
          {table.title}
        </text>
        {table.subtitleTone === 'amber' && <TriangleAlert x={position.x + 14} y={position.y + 25} size={10} color={AMBER_TEXT} />}
        {table.subtitle && (
          <text
            x={position.x + (table.subtitleTone === 'amber' ? 27 : 14)}
            y={position.y + 33}
            fontSize="9"
            fill={table.subtitleTone === 'amber' ? AMBER_TEXT : table.deprecated ? DEPRECATED_TEXT : MUTED}
            fontFamily={SANS}
          >
            {table.subtitle}
          </text>
        )}
        {table.keyLabel && (
          <text
            x={position.x + 14}
            y={position.y + (table.subtitle ? 45 : 29)}
            fontSize="9"
            fontWeight="600"
            fill={ACCENT}
            fontFamily={MONO}
          >
            {table.keyLabel}
          </text>
        )}
      </g>

      {/* 拖曳把手：整個表頭皆可拖曳 */}
      <rect
        x={position.x}
        y={position.y}
        width={table.width}
        height={layout.headerHeight}
        fill="transparent"
        style={{ cursor: dragging ? 'grabbing' : 'grab' }}
        onPointerDown={onPointerDownHeader}
        onPointerMove={onPointerMoveHeader}
        onPointerUp={onPointerUpHeader}
      />
      <GripVertical
        x={position.x + table.width - 20}
        y={position.y + layout.headerHeight - 15}
        size={12}
        color={table.deprecated ? DEPRECATED_TEXT : MUTED}
        style={{ pointerEvents: 'none' }}
      />

      {layout.rows.map(({ field, top: relativeTop, typeOwnLine }) => {
        const top = position.y + relativeTop;
        const colors = fieldColor(field.kind, emphasizeDerived);
        const isDerived = field.kind === 'derived' || field.kind === 'derived-key';
        const isKeyish = field.kind === 'key' || field.kind === 'derived-key';
        const rowKey = `${table.id}:${field.name}`;
        const rowHighlighted = highlightedFieldKeys.has(rowKey) || (hoveredField !== null && hoveredField.table === table.id && hoveredField.field === field.name);
        const showSparkles = emphasizeDerived && isDerived;
        const showKeyIcon = !emphasizeDerived && isKeyish;
        const nameX = position.x + (showKeyIcon || showSparkles ? 26 : 14);
        let cursor = top + 15;

        return (
          <g
            key={field.name}
            onMouseEnter={() => onHoverField(field.name)}
            onMouseLeave={onLeaveField}
          >
            {rowHighlighted && (
              <rect x={position.x + 2} y={top} width={table.width - 4} height={ROW_HEIGHT} rx={4} fill="#EEF2FF" />
            )}
            <rect x={position.x} y={top} width={table.width} height={ROW_HEIGHT} fill="transparent" />
            {showKeyIcon && <KeyRound x={position.x + 12} y={cursor - 9} size={10} color={colors.text} />}
            {showSparkles && <Sparkles x={position.x + 12} y={cursor - 9} size={10} color={colors.text} />}
            <text
              x={nameX}
              y={cursor}
              fontSize="11"
              fontWeight={colors.weight}
              fontStyle={colors.italic ? 'italic' : 'normal'}
              fill={colors.text}
              fontFamily={MONO}
            >
              {field.name}
            </text>
            {field.typeLabel && !typeOwnLine && (
              <text x={position.x + table.width - 14} y={cursor} textAnchor="end" fontSize="10" fill={colors.text} fontFamily={MONO}>
                {field.typeLabel}
              </text>
            )}
            {(() => {
              if (field.typeLabel && typeOwnLine) {
                cursor += NOTE_LINE_HEIGHT;
                return (
                  <text key="type-line" x={nameX} y={cursor} fontSize="9" fill={colors.text} fontFamily={MONO}>
                    {field.typeLabel}
                  </text>
                );
              }
              return null;
            })()}
            {field.note && (
              <text x={nameX} y={cursor + NOTE_LINE_HEIGHT} fontSize="9" fontStyle="italic" fill={emphasizeDerived && isDerived ? ACCENT : MUTED} fontFamily={SANS}>
                {field.note}
              </text>
            )}
          </g>
        );
      })}
    </g>
  );
}

function LegendMarkerSample({ kind, label }: { kind: MarkerKind; label: string }) {
  const id = `awerd-legend-${kind}`;
  return (
    <div className="flex items-center gap-1">
      <svg width="30" height="14" viewBox="0 0 30 14">
        <defs>
          <marker id={id} markerWidth="12" markerHeight="14" refX="10" refY="7" orient="auto">
            {kind === 'one' && (
              <>
                <line x1="5" y1="1" x2="5" y2="13" stroke={MUTED} strokeWidth="1.3" />
                <line x1="9" y1="1" x2="9" y2="13" stroke={MUTED} strokeWidth="1.3" />
              </>
            )}
            {kind === 'many' && <path d="M 0 7 L 12 1 M 0 7 L 12 7 M 0 7 L 12 13" fill="none" stroke={MUTED} strokeWidth="1.3" />}
            {kind === 'zero-one' && (
              <>
                <circle cx="5" cy="7" r="4" fill={PAPER} stroke={MUTED} strokeWidth="1.2" />
                <line x1="13" y1="1" x2="13" y2="13" stroke={MUTED} strokeWidth="1.3" />
              </>
            )}
          </marker>
        </defs>
        <line x1="2" y1="7" x2="20" y2="7" stroke={MUTED} strokeWidth="1.3" markerEnd={`url(#${id})`} />
      </svg>
      <span className="text-xs text-slate-500">{label}</span>
    </div>
  );
}

// ---------------------------------------------------------------------------
// 根元件
// ---------------------------------------------------------------------------

export default function AnnotationWorkspaceErd() {
  const [positions, setPositions] = useState<PositionMap>(INITIAL_POSITIONS);
  const [hoveredTable, setHoveredTable] = useState<TableId | null>(null);
  const [hoveredField, setHoveredField] = useState<HoverField | null>(null);
  const [emphasizeDerived, setEmphasizeDerived] = useState(false);
  const [dragTableId, setDragTableId] = useState<TableId | null>(null);
  const svgRef = useRef<SVGSVGElement>(null);
  const dragOriginRef = useRef<{ pointerId: number; clientX: number; clientY: number; startX: number; startY: number } | null>(null);

  const highlightedFieldKeys = useMemo(() => {
    const set = new Set<string>();
    if (!hoveredField) return set;
    for (const rel of RELATIONS) {
      if (rel.from === hoveredField.table && rel.fromField === hoveredField.field && rel.toField) {
        set.add(`${rel.to}:${rel.toField}`);
      }
      if (rel.to === hoveredField.table && rel.toField === hoveredField.field && rel.fromField) {
        set.add(`${rel.from}:${rel.fromField}`);
      }
    }
    return set;
  }, [hoveredField]);

  const highlightedWholeTables = useMemo(() => {
    const set = new Set<TableId>();
    if (!hoveredField) return set;
    for (const rel of RELATIONS) {
      if (rel.from === hoveredField.table && rel.fromField === hoveredField.field && !rel.toField) set.add(rel.to);
      if (rel.to === hoveredField.table && rel.toField === hoveredField.field && !rel.fromField) set.add(rel.from);
    }
    return set;
  }, [hoveredField]);

  const handlePointerDownHeader = (tableId: TableId) => (event: ReactPointerEvent<SVGRectElement>) => {
    event.currentTarget.setPointerCapture(event.pointerId);
    dragOriginRef.current = {
      pointerId: event.pointerId,
      clientX: event.clientX,
      clientY: event.clientY,
      startX: positions[tableId].x,
      startY: positions[tableId].y,
    };
    setDragTableId(tableId);
  };

  const handlePointerMoveHeader = (tableId: TableId) => (event: ReactPointerEvent<SVGRectElement>) => {
    const origin = dragOriginRef.current;
    if (!origin || origin.pointerId !== event.pointerId || dragTableId !== tableId) return;
    const svg = svgRef.current;
    if (!svg) return;
    const rect = svg.getBoundingClientRect();
    if (rect.width === 0) return;
    const ratio = VIEW_WIDTH / rect.width;
    const dx = (event.clientX - origin.clientX) * ratio;
    const dy = (event.clientY - origin.clientY) * ratio;
    setPositions((prev) => ({ ...prev, [tableId]: { x: origin.startX + dx, y: origin.startY + dy } }));
  };

  const handlePointerUpHeader = () => (event: ReactPointerEvent<SVGRectElement>) => {
    if (dragOriginRef.current && event.currentTarget.hasPointerCapture(dragOriginRef.current.pointerId)) {
      event.currentTarget.releasePointerCapture(dragOriginRef.current.pointerId);
    }
    dragOriginRef.current = null;
    setDragTableId(null);
  };

  return (
    <div className="awerd-root not-prose space-y-4">
      <style dangerouslySetInnerHTML={{ __html: SCOPED_CSS }} />

      <div className="flex items-center justify-between gap-2 flex-wrap">
        <p className="text-sm text-slate-600">拖曳表頭可移動表格；hover 表格或欄位可看相關連線。</p>
        <button
          type="button"
          role="switch"
          aria-checked={emphasizeDerived}
          onClick={() => setEmphasizeDerived((v) => !v)}
          className={clsx(
            'flex items-center gap-1 rounded-lg border px-3 py-1.5 text-sm font-medium transition-colors',
            emphasizeDerived ? 'border-indigo-500 bg-indigo-50 text-indigo-600' : 'border bg-white text-slate-600'
          )}
        >
          {emphasizeDerived ? <Sparkles size={14} /> : <Database size={14} />}
          凸顯推導欄位
        </button>
      </div>

      <div style={{ overflowX: 'auto' }}>
        <svg
          ref={svgRef}
          viewBox={`0 0 ${VIEW_WIDTH} ${VIEW_HEIGHT}`}
          role="img"
          aria-label="標註工作區資料實體關係圖：TaskProfile 到 DisputeItem 共 11 個實體，實線為原文明寫的關聯，虛線為推導關聯"
          style={{ width: '100%', minWidth: 1600, display: 'block', fontFamily: SANS }}
        >
          <rect width="100%" height="100%" fill={PAPER} />
          <defs>{renderMarkers()}</defs>

          {RELATIONS.map((rel) => (
            <RelationLine
              key={rel.id}
              rel={rel}
              positions={positions}
              hoveredTable={hoveredTable}
              hoveredField={hoveredField}
              emphasizeDerived={emphasizeDerived}
            />
          ))}

          {TABLES.map((table) => (
            <TableCard
              key={table.id}
              table={table}
              position={positions[table.id]}
              hovered={hoveredTable === table.id}
              hoveredField={hoveredField}
              highlightedFieldKeys={highlightedFieldKeys}
              highlightedWholeTables={highlightedWholeTables}
              emphasizeDerived={emphasizeDerived}
              onHoverTable={() => setHoveredTable(table.id)}
              onLeaveTable={() => {
                setHoveredTable(null);
                setHoveredField(null);
              }}
              onHoverField={(fieldName) => setHoveredField({ table: table.id, field: fieldName })}
              onLeaveField={() => setHoveredField(null)}
              onPointerDownHeader={handlePointerDownHeader(table.id)}
              onPointerMoveHeader={handlePointerMoveHeader(table.id)}
              onPointerUpHeader={handlePointerUpHeader()}
              dragging={dragTableId === table.id}
            />
          ))}
        </svg>
      </div>

      <div className="flex items-center gap-4 flex-wrap">
        <div className="flex items-center gap-1">
          <svg width="30" height="10" viewBox="0 0 30 10">
            <line x1="2" y1="5" x2="28" y2="5" stroke={MARKER_COLORS.default} strokeWidth="1.5" />
          </svg>
          <span className="text-xs text-slate-500">實線 = 原文明寫</span>
        </div>
        <div className="flex items-center gap-1">
          <svg width="30" height="10" viewBox="0 0 30 10">
            <line x1="2" y1="5" x2="28" y2="5" stroke={MARKER_COLORS.mutedDefault} strokeWidth="1.5" strokeDasharray="5,4" />
          </svg>
          <span className="text-xs text-slate-500">虛線 = 推導</span>
        </div>
        <div className="flex items-center gap-1">
          <div style={{ width: 14, height: 14, borderRadius: 4, border: `1px solid ${DEPRECATED_BORDER}`, background: DEPRECATED_BG, opacity: 0.6 }} />
          <span className="text-xs text-slate-500">灰階 = 已廢止 v4.0.0</span>
        </div>
        <div className="flex items-center gap-1">
          <KeyRound size={12} color={INK} />
          <span className="text-xs text-slate-500">定址或維度鍵</span>
        </div>
        <LegendMarkerSample kind="one" label="一" />
        <LegendMarkerSample kind="many" label="多" />
        <LegendMarkerSample kind="zero-one" label="零或一" />
      </div>
    </div>
  );
}
