// 本檔為 generated view——請勿手動編輯
// Generated by NoteCraft @ai-visualize (content-visualize skill); regenerate from the marker in specs/annotation/015-annotation-workspace/diagrams.mdx.

import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type KeyboardEvent as ReactKeyboardEvent,
  type PointerEvent as ReactPointerEvent,
} from 'react';
import { motion, AnimatePresence, useReducedMotion } from 'motion/react';
import {
  ZoomIn,
  ZoomOut,
  Maximize,
  RotateCcw,
  ChevronDown,
  ChevronRight,
  X,
  StickyNote,
  KeyRound,
} from 'lucide-react';

// ---------------------------------------------------------------------------
// SCOPED_CSS —— NoteCraft 的 Tailwind JIT 掃描不到 .notecraft/components/ 下的
// class，本檔不用 Tailwind，全部樣式限定在 .dbe-root 底下、以 CSS 自訂屬性
// 供亮／暗色模式切換。SVG 內部著色透過行內 style 參照這些自訂屬性。
// ---------------------------------------------------------------------------

const SCOPED_CSS = `
.dbe-root {
  --dbe-bg: #FFFFFF;
  --dbe-canvas-bg: #F5F3FF;
  --dbe-surface: #FFFFFF;
  --dbe-border: #E2E8F0;
  --dbe-border-muted: #F1F5F9;
  --dbe-ink: #1E1B4B;
  --dbe-text-soft: #64748B;
  --dbe-text-muted: #94A3B8;
  --dbe-primary: #6366F1;
  --dbe-primary-soft-bg: #EEF2FF;
  --dbe-primary-border: #C7D2FE;
  --dbe-header-bg: #EEF2FF;
  --dbe-header-text: #4338CA;
  --dbe-accent: #6366F1;
  --dbe-marker-default: #475569;
  --dbe-marker-dim: #CBD5E1;
  --dbe-badge-pk-bg: #EEF2FF;
  --dbe-badge-pk-text: #4338CA;
  --dbe-badge-fk-bg: #EFF6FF;
  --dbe-badge-fk-text: #1D4ED8;
  --dbe-badge-nn-bg: #F1F5F9;
  --dbe-badge-nn-text: #475569;
  --dbe-dot: #DCD6F7;
  --dbe-shadow-card: 0 1px 2px rgba(0, 0, 0, 0.05);
  --dbe-font-sans: 'Inter', 'Noto Sans TC', -apple-system, BlinkMacSystemFont, sans-serif;
  --dbe-font-mono: 'JetBrains Mono', ui-monospace, Menlo, monospace;

  position: relative;
  display: flex;
  flex-direction: column;
  height: 640px;
  width: 100%;
  overflow: hidden;
  background: var(--dbe-bg);
  color: var(--dbe-ink);
  font-family: var(--dbe-font-sans);
  border-radius: 8px;
}

@media (prefers-color-scheme: dark) {
  .dbe-root {
    --dbe-bg: #0B0B12;
    --dbe-canvas-bg: #0B0B12;
    --dbe-surface: #16161F;
    --dbe-border: #2A2A35;
    --dbe-border-muted: #1F1F28;
    --dbe-ink: #E2E8F0;
    --dbe-text-soft: #A1A1AA;
    --dbe-text-muted: #9CA3AF;
    --dbe-primary: #818CF8;
    --dbe-primary-soft-bg: #1E1B4B;
    --dbe-primary-border: #3730A3;
    --dbe-header-bg: #1E1B4B;
    --dbe-header-text: #C7D2FE;
    --dbe-accent: #818CF8;
    --dbe-marker-default: #A1A1AA;
    --dbe-marker-dim: #3F3F4A;
    --dbe-badge-pk-bg: #1E1B4B;
    --dbe-badge-pk-text: #C7D2FE;
    --dbe-badge-fk-bg: #0F1F33;
    --dbe-badge-fk-text: #60A5FA;
    --dbe-badge-nn-bg: #1F1F28;
    --dbe-badge-nn-text: #A1A1AA;
    --dbe-dot: #22222E;
  }
}

:is(html.dark, [data-theme='dark']) .dbe-root {
  --dbe-bg: #0B0B12;
  --dbe-canvas-bg: #0B0B12;
  --dbe-surface: #16161F;
  --dbe-border: #2A2A35;
  --dbe-border-muted: #1F1F28;
  --dbe-ink: #E2E8F0;
  --dbe-text-soft: #A1A1AA;
  --dbe-text-muted: #9CA3AF;
  --dbe-primary: #818CF8;
  --dbe-primary-soft-bg: #1E1B4B;
  --dbe-primary-border: #3730A3;
  --dbe-header-bg: #1E1B4B;
  --dbe-header-text: #C7D2FE;
  --dbe-accent: #818CF8;
  --dbe-marker-default: #A1A1AA;
  --dbe-marker-dim: #3F3F4A;
  --dbe-badge-pk-bg: #1E1B4B;
  --dbe-badge-pk-text: #C7D2FE;
  --dbe-badge-fk-bg: #0F1F33;
  --dbe-badge-fk-text: #60A5FA;
  --dbe-badge-nn-bg: #1F1F28;
  --dbe-badge-nn-text: #A1A1AA;
  --dbe-dot: #22222E;
}

.dbe-root * { box-sizing: border-box; }
.dbe-root p { margin: 0; }
.dbe-root button {
  font: inherit;
  color: inherit;
  background: none;
  border: 0;
  cursor: pointer;
}
.dbe-root button:disabled { cursor: not-allowed; opacity: 0.5; }

.dbe-toolbar {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 8px;
  padding: 8px 12px;
  border-bottom: 1px solid var(--dbe-border);
  background: var(--dbe-surface);
  flex: 0 0 auto;
}

.dbe-btn {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 5px 10px;
  border-radius: 8px;
  border: 1px solid var(--dbe-border);
  background: var(--dbe-surface);
  color: var(--dbe-text-soft);
  font-size: 12px;
  font-weight: 500;
  transition: background-color 160ms ease-out, border-color 160ms ease-out, color 160ms ease-out;
}
.dbe-btn:hover { color: var(--dbe-ink); border-color: var(--dbe-primary-border); }
.dbe-btn:focus-visible { outline: 2px solid var(--dbe-primary); outline-offset: 1px; }

.dbe-seg {
  display: inline-flex;
  border: 1px solid var(--dbe-border);
  border-radius: 8px;
  overflow: hidden;
}
.dbe-seg-btn {
  padding: 5px 10px;
  font-size: 12px;
  font-weight: 500;
  color: var(--dbe-text-soft);
  border-right: 1px solid var(--dbe-border);
  transition: background-color 160ms ease-out, color 160ms ease-out;
}
.dbe-seg-btn:last-child { border-right: 0; }
.dbe-seg-btn:hover { color: var(--dbe-ink); }
.dbe-seg-btn:focus-visible { outline: 2px solid var(--dbe-primary); outline-offset: -2px; }
.dbe-seg-btn[aria-pressed='true'] {
  background: var(--dbe-primary-soft-bg);
  color: var(--dbe-primary);
}

.dbe-spacer { flex: 1 1 auto; }

.dbe-canvas-wrap {
  position: relative;
  flex: 1 1 auto;
  min-height: 0;
  overflow: hidden;
  background: var(--dbe-canvas-bg);
}

.dbe-chip {
  flex: 0 0 auto;
  min-height: 32px;
  padding: 7px 12px;
  border-bottom: 1px solid var(--dbe-border);
  background: var(--dbe-surface);
  font-size: 12px;
  line-height: 18px;
  font-family: var(--dbe-font-mono);
  color: var(--dbe-ink);
  pointer-events: none;
}

.dbe-panel {
  position: absolute;
  top: 10px;
  right: 10px;
  bottom: 10px;
  z-index: 3;
  width: 300px;
  max-width: calc(100% - 24px);
  display: flex;
  flex-direction: column;
  border-radius: 12px;
  border: 1px solid var(--dbe-border);
  background: var(--dbe-surface);
  box-shadow: var(--dbe-shadow-card);
  overflow: hidden;
}
.dbe-panel:focus-visible { outline: 2px solid var(--dbe-primary); outline-offset: -2px; }
.dbe-panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 8px;
  padding: 10px 12px;
  border-bottom: 1px solid var(--dbe-border);
}
.dbe-panel-title {
  font-family: var(--dbe-font-mono);
  font-size: 14px;
  font-weight: 600;
  color: var(--dbe-ink);
}
.dbe-panel-close {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 26px;
  height: 26px;
  border-radius: 8px;
  color: var(--dbe-text-soft);
}
.dbe-panel-close:hover { background: var(--dbe-primary-soft-bg); color: var(--dbe-primary); }
.dbe-panel-close:focus-visible { outline: 2px solid var(--dbe-primary); outline-offset: 1px; }
.dbe-panel-body {
  flex: 1 1 auto;
  min-height: 0;
  overflow: auto;
  padding: 8px;
}
.dbe-table {
  width: 100%;
  border-collapse: collapse;
  font-family: var(--dbe-font-mono);
  font-size: 11px;
}
.dbe-table th,
.dbe-table td {
  padding: 6px 8px;
  text-align: left;
  border-bottom: 1px solid var(--dbe-border-muted);
  white-space: nowrap;
}
.dbe-table th {
  color: var(--dbe-text-soft);
  font-weight: 600;
  position: sticky;
  top: 0;
  background: var(--dbe-surface);
}
.dbe-table td { color: var(--dbe-ink); }
.dbe-table td.dbe-empty { color: var(--dbe-text-muted); }

.dbe-live {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

.dbe-chip.dbe-chip-idle { color: var(--dbe-text-muted); font-family: inherit; }
.dbe-tooltip-wrap { position: relative; display: inline-flex; }
.dbe-note-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 18px;
  height: 18px;
  border-radius: 4px;
  color: var(--dbe-text-muted);
}
.dbe-note-btn:hover { color: var(--dbe-primary); background: var(--dbe-primary-soft-bg); }
.dbe-note-btn:focus-visible { outline: 2px solid var(--dbe-primary); outline-offset: 1px; }
.dbe-expand-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 22px;
  height: 22px;
  border-radius: 6px;
  color: var(--dbe-header-text);
}
.dbe-expand-btn:hover:not(:disabled) { background: rgba(99, 102, 241, 0.16); }
.dbe-expand-btn:focus-visible { outline: 2px solid var(--dbe-primary); outline-offset: 1px; }

@media (prefers-reduced-motion: reduce) {
  .dbe-btn,
  .dbe-seg-btn,
  .dbe-panel-close,
  .dbe-note-btn,
  .dbe-expand-btn {
    transition: none;
  }
}
`;

// ---------------------------------------------------------------------------
// 資料模型 —— 唯一來源是標記 prompt 內逐字給出的 DBML；不得增刪改名或推測。
// ---------------------------------------------------------------------------

type ColumnType = 'integer' | 'varchar' | 'text' | 'timestamp';

interface ColumnSpec {
  name: string;
  type: ColumnType;
  notNull?: boolean;
  note?: string;
}

type TableId = 'users' | 'posts' | 'follows';

interface TableSpec {
  id: TableId;
  name: string;
  columns: ColumnSpec[];
}

type ManyKind = 'many' | 'manyZeroOrMany';

const CHANNEL_SPACING = 26;

interface RefEnd {
  table: TableId;
  column: string;
}

interface RefSpec {
  id: string;
  label: string;
  many: RefEnd;
  one: RefEnd;
  manyKind: ManyKind;
  direction: string;
  // 同側繞行時額外外推的通道距離，讓共用同一張表的關聯線彼此分開。
  channelOffset: number;
}

type RecordRow = Record<string, string | number>;

// PK 定址鍵——單一事實來源，欄位上的 PK 徽章一律由此推導，不重複標記在 ColumnSpec 上。
const PK_COLUMNS: Record<TableId, string[]> = {
  users: ['id'],
  posts: ['id'],
  follows: [],
};

// 關聯——單一事實來源，欄位上的 FK 徽章與連線基數皆由此推導。
const REFS: RefSpec[] = [
  {
    id: 'user_posts',
    label: 'user_posts',
    many: { table: 'posts', column: 'user_id' },
    one: { table: 'users', column: 'id' },
    manyKind: 'many',
    direction: 'posts.user_id → users.id',
    channelOffset: 0,
  },
  {
    id: 'following_user',
    label: 'following_user',
    many: { table: 'follows', column: 'following_user_id' },
    one: { table: 'users', column: 'id' },
    manyKind: 'manyZeroOrMany',
    direction: 'users.id → follows.following_user_id',
    channelOffset: 0,
  },
  {
    id: 'followed_user',
    label: 'followed_user',
    many: { table: 'follows', column: 'followed_user_id' },
    one: { table: 'users', column: 'id' },
    manyKind: 'manyZeroOrMany',
    direction: 'users.id → follows.followed_user_id',
    channelOffset: CHANNEL_SPACING,
  },
];

const TABLES: TableSpec[] = [
  {
    id: 'users',
    name: 'users',
    columns: [
      { name: 'id', type: 'integer' },
      { name: 'username', type: 'varchar' },
      { name: 'role', type: 'varchar' },
      { name: 'created_at', type: 'timestamp' },
    ],
  },
  {
    id: 'posts',
    name: 'posts',
    columns: [
      { name: 'id', type: 'integer' },
      { name: 'title', type: 'varchar' },
      { name: 'body', type: 'text', note: 'Content of the post' },
      { name: 'user_id', type: 'integer', notNull: true },
      { name: 'status', type: 'varchar' },
      { name: 'created_at', type: 'timestamp' },
    ],
  },
  {
    id: 'follows',
    name: 'follows',
    columns: [
      { name: 'following_user_id', type: 'integer', notNull: true },
      { name: 'followed_user_id', type: 'integer', notNull: true },
      { name: 'created_at', type: 'timestamp' },
    ],
  },
];

const RECORDS: Record<TableId, RecordRow[]> = {
  users: [
    { id: 0, username: 'Alice', role: 'admin' },
    { id: 1, username: 'Bob', role: 'moderator' },
    { id: 2, username: 'Candice', role: 'moderator' },
    { id: 3, username: 'David', role: 'member' },
  ],
  follows: [
    { following_user_id: 1, followed_user_id: 0, created_at: '2026-01-01' },
    { following_user_id: 3, followed_user_id: 2, created_at: '2026-02-28' },
  ],
  posts: [
    { id: 0, title: 'Welcome to the forum!', user_id: 0 },
    { id: 1, title: 'Guidelines', user_id: 1 },
    { id: 2, title: 'Hello all!', user_id: 3 },
  ],
};

const TABLES_BY_ID: Record<TableId, TableSpec> = TABLES.reduce((acc, table) => {
  acc[table.id] = table;
  return acc;
}, {} as Record<TableId, TableSpec>);

function isPrimaryKeyColumn(tableId: TableId, columnName: string): boolean {
  return PK_COLUMNS[tableId].includes(columnName);
}
function isForeignKeyColumn(tableId: TableId, columnName: string): boolean {
  return REFS.some((ref) => ref.many.table === tableId && ref.many.column === columnName);
}
function isKeyColumn(tableId: TableId, columnName: string): boolean {
  return isPrimaryKeyColumn(tableId, columnName) || isForeignKeyColumn(tableId, columnName);
}
function columnBadges(tableId: TableId, col: ColumnSpec): Array<'PK' | 'FK' | 'NN'> {
  const badges: Array<'PK' | 'FK' | 'NN'> = [];
  if (isPrimaryKeyColumn(tableId, col.name)) badges.push('PK');
  if (isForeignKeyColumn(tableId, col.name)) badges.push('FK');
  if (col.notNull) badges.push('NN');
  return badges;
}

// ---------------------------------------------------------------------------
// 版面常數與量測——以固定字元寬推算卡片寬，欄名絕不截斷。
// ---------------------------------------------------------------------------

const CHAR_W = 7.2; // px / mono 字元 @ 12px（依規格）
const BADGE_CHAR_W = 5.4;
const BADGE_PAD_X = 5;
const BADGE_GAP = 4;
const ROW_PAD_X = 14;
const NAME_TYPE_GAP = 20;
const ROW_HEIGHT = 28;
const HEADER_HEIGHT = 36;
const CARD_MIN_WIDTH = 200;
const CARD_RADIUS = 8;
const STUB = 28;
const MIN_K = 0.4;
const MAX_K = 2.5;

function badgeWidth(text: string): number {
  return text.length * BADGE_CHAR_W + BADGE_PAD_X * 2;
}
function rowContentWidth(tableId: TableId, col: ColumnSpec): number {
  const badges = columnBadges(tableId, col);
  const badgesWidth = badges.reduce((sum, b) => sum + badgeWidth(b) + BADGE_GAP, 0);
  const nameWidth = col.name.length * CHAR_W;
  const typeWidth = col.type.length * CHAR_W;
  return nameWidth + badgesWidth + NAME_TYPE_GAP + typeWidth;
}
function computeCardWidth(table: TableSpec): number {
  const headerWidth = table.name.length * 8.6 + 56;
  const rowsWidth = table.columns.reduce((max, col) => Math.max(max, rowContentWidth(table.id, col)), 0);
  return Math.ceil(Math.max(CARD_MIN_WIDTH, headerWidth, rowsWidth + ROW_PAD_X * 2));
}

const TABLE_WIDTHS: Record<TableId, number> = TABLES.reduce((acc, table) => {
  acc[table.id] = computeCardWidth(table);
  return acc;
}, {} as Record<TableId, number>);

type PositionMap = Record<TableId, { x: number; y: number }>;

const LAYOUT_GAP_X = 140;
const LAYOUT_GAP_Y = 96;
const USERS_INITIAL_HEIGHT = HEADER_HEIGHT + TABLES_BY_ID.users.columns.length * ROW_HEIGHT;

const INITIAL_POSITIONS: PositionMap = {
  users: { x: 60, y: 48 },
  posts: { x: 60 + TABLE_WIDTHS.users + LAYOUT_GAP_X, y: 48 },
  follows: { x: 60, y: 48 + USERS_INITIAL_HEIGHT + LAYOUT_GAP_Y },
};

type Level = 'all' | 'keys' | 'tables';

const LEVEL_LABELS: Record<Level, string> = {
  all: '全部欄位',
  keys: '僅鍵值',
  tables: '僅資料表',
};

function visibleColumns(table: TableSpec, level: Level, collapsed: Set<TableId>): ColumnSpec[] {
  if (level === 'tables') return [];
  if (level === 'keys') return table.columns.filter((c) => isKeyColumn(table.id, c.name));
  if (collapsed.has(table.id)) return table.columns.filter((c) => isKeyColumn(table.id, c.name));
  return table.columns;
}
function tableTotalHeight(table: TableSpec, level: Level, collapsed: Set<TableId>): number {
  return HEADER_HEIGHT + visibleColumns(table, level, collapsed).length * ROW_HEIGHT;
}

interface Rect {
  x: number;
  y: number;
  w: number;
  h: number;
}
function getTableRect(table: TableSpec, positions: PositionMap, level: Level, collapsed: Set<TableId>): Rect {
  const pos = positions[table.id];
  return { x: pos.x, y: pos.y, w: TABLE_WIDTHS[table.id], h: tableTotalHeight(table, level, collapsed) };
}

function columnAnchorY(
  tableId: TableId,
  columnName: string,
  positions: PositionMap,
  level: Level,
  collapsed: Set<TableId>
): number {
  const table = TABLES_BY_ID[tableId];
  const pos = positions[tableId];
  const cols = visibleColumns(table, level, collapsed);
  const idx = cols.findIndex((c) => c.name === columnName);
  if (idx === -1) return pos.y + HEADER_HEIGHT / 2;
  return pos.y + HEADER_HEIGHT + idx * ROW_HEIGHT + ROW_HEIGHT / 2;
}

// ---------------------------------------------------------------------------
// 關聯路由——正交路徑、離開卡片一律走水平 stub，遇卡片阻擋換邊或改道。
// ---------------------------------------------------------------------------

type Side = 'left' | 'right';
interface Point {
  x: number;
  y: number;
}

function segmentHitsRect(x1: number, y1: number, x2: number, y2: number, rect: Rect, margin = 8): boolean {
  const rx1 = rect.x - margin;
  const ry1 = rect.y - margin;
  const rx2 = rect.x + rect.w + margin;
  const ry2 = rect.y + rect.h + margin;
  if (y1 === y2) {
    const y = y1;
    if (y < ry1 || y > ry2) return false;
    const xMin = Math.min(x1, x2);
    const xMax = Math.max(x1, x2);
    return xMax >= rx1 && xMin <= rx2;
  }
  if (x1 === x2) {
    const x = x1;
    if (x < rx1 || x > rx2) return false;
    const yMin = Math.min(y1, y2);
    const yMax = Math.max(y1, y2);
    return yMax >= ry1 && yMin <= ry2;
  }
  return false;
}

function buildRoutePoints(sA: Side, sB: Side, edgeA: Point, edgeB: Point, channelOffset: number): Point[] | null {
  const stubAx = sA === 'right' ? edgeA.x + STUB : edgeA.x - STUB;
  const stubBx = sB === 'right' ? edgeB.x + STUB : edgeB.x - STUB;
  let channelX: number;
  if (sA === sB) {
    const outward = STUB + channelOffset;
    channelX = sA === 'right' ? Math.max(stubAx, stubBx) + outward : Math.min(stubAx, stubBx) - outward;
  } else {
    // 對向出線時通道必須落在兩個 stub 之間，否則線會折返疊在自己身上。
    if (sA === 'right' ? stubAx > stubBx : stubAx < stubBx) return null;
    channelX = (stubAx + stubBx) / 2;
  }
  return [
    { x: edgeA.x, y: edgeA.y },
    { x: stubAx, y: edgeA.y },
    { x: channelX, y: edgeA.y },
    { x: channelX, y: edgeB.y },
    { x: stubBx, y: edgeB.y },
    { x: edgeB.x, y: edgeB.y },
  ];
}

function routeLength(points: Point[]): number {
  let total = 0;
  for (let i = 0; i < points.length - 1; i++) {
    total += Math.abs(points[i + 1].x - points[i].x) + Math.abs(points[i + 1].y - points[i].y);
  }
  return total;
}

function buildRoute(
  fromTableId: TableId,
  fromColumn: string,
  toTableId: TableId,
  toColumn: string,
  positions: PositionMap,
  level: Level,
  collapsed: Set<TableId>,
  channelOffset: number
): Point[] {
  const fromRect = getTableRect(TABLES_BY_ID[fromTableId], positions, level, collapsed);
  const toRect = getTableRect(TABLES_BY_ID[toTableId], positions, level, collapsed);
  const fromY = columnAnchorY(fromTableId, fromColumn, positions, level, collapsed);
  const toY = columnAnchorY(toTableId, toColumn, positions, level, collapsed);
  const allRects = TABLES.map((t) => getTableRect(t, positions, level, collapsed));
  const otherRects = TABLES.filter((t) => t.id !== fromTableId && t.id !== toTableId).map((t) =>
    getTableRect(t, positions, level, collapsed)
  );
  const sides: Side[] = ['right', 'left'];
  const edgeOf = (rect: Rect, side: Side, y: number): Point => ({
    x: side === 'right' ? rect.x + rect.w : rect.x,
    y,
  });

  // 候選路線：四種出線側組合；stub 段只跟其他表比對，中段連兩端的表一起比對。
  // 取所有不相交候選中最短的一條；全部相交時退回最短的一條，保持決定性。
  let best: Point[] | null = null;
  let bestClear = false;
  for (const sA of sides) {
    for (const sB of sides) {
      const points = buildRoutePoints(sA, sB, edgeOf(fromRect, sA, fromY), edgeOf(toRect, sB, toY), channelOffset);
      if (!points) continue;
      let clear = true;
      for (let i = 0; i < points.length - 1 && clear; i++) {
        const isStub = i === 0 || i === points.length - 2;
        const rects = isStub ? otherRects : allRects;
        const margin = isStub ? 8 : 4;
        for (const rect of rects) {
          if (segmentHitsRect(points[i].x, points[i].y, points[i + 1].x, points[i + 1].y, rect, margin)) {
            clear = false;
            break;
          }
        }
      }
      const better =
        best === null ||
        (clear && !bestClear) ||
        (clear === bestClear && routeLength(points) < routeLength(best));
      if (better) {
        best = points;
        bestClear = clear;
      }
    }
  }
  return best ?? [];
}

// 關聯標籤放在垂直通道外側，不壓線、不壓卡片；同側多條線的標籤一律對齊到最外側通道。
function routeLabelBox(points: Point[], relSpec: RefSpec): { x: number; y: number; w: number; h: number; anchorX: number; textAnchor: 'start' | 'end' } {
  const w = relSpec.label.length * 5.6 + 8;
  const h = 14;
  const channelX = points[2].x;
  const channelGoesLeft = channelX < points[0].x && channelX < points[5].x;
  const y = (points[2].y + points[3].y) / 2 - h / 2;
  if (channelGoesLeft) {
    const right = channelX - 6 - (CHANNEL_SPACING - relSpec.channelOffset);
    return { x: right - w, y, w, h, anchorX: right - 4, textAnchor: 'end' };
  }
  const channelGoesRight = channelX > points[0].x && channelX > points[5].x;
  if (channelGoesRight) {
    const left = channelX + 6 + (CHANNEL_SPACING - relSpec.channelOffset);
    return { x: left, y, w, h, anchorX: left + 4, textAnchor: 'start' };
  }
  // 對向出線：通道位於兩表之間，標籤置中壓在自己的垂直段上（底色遮住的只有自己的線）。
  return { x: channelX - w / 2, y, w, h, anchorX: channelX + w / 2 - 4, textAnchor: 'end' };
}

// 基數符號直接依端點與出線方向畫成路徑，不用 <marker>（起點方向會朝內、被卡片蓋住）。
function cardinalityGlyph(edge: Point, stub: Point, kind: ManyKind | 'one'): { paths: string[]; circle: Point | null } {
  const dir = stub.x > edge.x ? 1 : -1;
  const { x, y } = edge;
  if (kind === 'one') {
    return { paths: [`M ${x + dir * 8} ${y - 6} V ${y + 6}`, `M ${x + dir * 12} ${y - 6} V ${y + 6}`], circle: null };
  }
  const foot = `M ${x + dir * 12} ${y} L ${x} ${y - 6} M ${x + dir * 12} ${y} L ${x} ${y} M ${x + dir * 12} ${y} L ${x} ${y + 6}`;
  if (kind === 'many') return { paths: [foot, `M ${x + dir * 15} ${y - 6} V ${y + 6}`], circle: null };
  return { paths: [foot], circle: { x: x + dir * 18, y } };
}

function pointsToPath(points: Point[]): string {
  return points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

// ---------------------------------------------------------------------------
// 高亮／聚焦狀態
// ---------------------------------------------------------------------------

type FocusKind = 'table' | 'column' | 'ref';
interface FocusState {
  kind: FocusKind;
  id: string;
}
interface ActiveSet {
  tables: Set<TableId>;
  columns: Set<string>;
  refs: Set<string>;
}

function computeActiveSet(focus: FocusState | null): ActiveSet {
  const tables = new Set<TableId>();
  const columns = new Set<string>();
  const refs = new Set<string>();
  if (!focus) return { tables, columns, refs };

  const addRef = (ref: RefSpec) => {
    refs.add(ref.id);
    tables.add(ref.many.table);
    tables.add(ref.one.table);
    columns.add(`${ref.many.table}.${ref.many.column}`);
    columns.add(`${ref.one.table}.${ref.one.column}`);
  };

  if (focus.kind === 'table') {
    const tableId = focus.id as TableId;
    tables.add(tableId);
    for (const ref of REFS) {
      if (ref.many.table === tableId || ref.one.table === tableId) addRef(ref);
    }
  } else if (focus.kind === 'column') {
    columns.add(focus.id);
    for (const ref of REFS) {
      const manyKey = `${ref.many.table}.${ref.many.column}`;
      const oneKey = `${ref.one.table}.${ref.one.column}`;
      if (manyKey === focus.id || oneKey === focus.id) addRef(ref);
    }
  } else {
    const ref = REFS.find((r) => r.id === focus.id);
    if (ref) addRef(ref);
  }
  return { tables, columns, refs };
}

function statusChipText(focus: FocusState | null): string | null {
  if (!focus) return null;
  if (focus.kind === 'ref') {
    const ref = REFS.find((r) => r.id === focus.id);
    return ref ? `${ref.label}：${ref.direction}` : null;
  }
  if (focus.kind === 'table') {
    const relevant = REFS.filter((r) => r.many.table === focus.id || r.one.table === focus.id);
    if (relevant.length === 0) return `${focus.id}：無關聯`;
    return relevant.map((r) => `${r.label}（${r.direction}）`).join('；');
  }
  const relevant = REFS.filter(
    (r) => `${r.many.table}.${r.many.column}` === focus.id || `${r.one.table}.${r.one.column}` === focus.id
  );
  if (relevant.length === 0) return null;
  return relevant.map((r) => `${r.label}（${r.direction}）`).join('；');
}

type LineColorKey = 'default' | 'dim' | 'accent';
const LINE_COLORS: Record<LineColorKey, string> = {
  default: 'var(--dbe-marker-default)',
  dim: 'var(--dbe-marker-dim)',
  accent: 'var(--dbe-accent)',
};

// ---------------------------------------------------------------------------
// 子元件：關聯線
// ---------------------------------------------------------------------------

function RelationLine({
  relation: relSpec,
  positions,
  level,
  collapsed,
  active,
  anyFocusActive,
  onEnter,
  onLeave,
  onActivate,
}: {
  relation: RefSpec;
  positions: PositionMap;
  level: Level;
  collapsed: Set<TableId>;
  active: boolean;
  anyFocusActive: boolean;
  onEnter: () => void;
  onLeave: () => void;
  onActivate: () => void;
}) {
  const points = useMemo(
    () =>
      buildRoute(
        relSpec.many.table,
        relSpec.many.column,
        relSpec.one.table,
        relSpec.one.column,
        positions,
        level,
        collapsed,
        relSpec.channelOffset
      ),
    [relSpec, positions, level, collapsed]
  );
  const d = pointsToPath(points);
  const colorKey: LineColorKey = anyFocusActive ? (active ? 'accent' : 'dim') : 'default';
  const color = LINE_COLORS[colorKey];
  const opacity = anyFocusActive ? (active ? 1 : 0.35) : 1;
  const strokeWidth = anyFocusActive && active ? 2.4 : 1.5;
  const label = routeLabelBox(points, relSpec);
  const manyGlyph = cardinalityGlyph(points[0], points[1], relSpec.manyKind);
  const oneGlyph = cardinalityGlyph(points[5], points[4], 'one');
  const showLabel = active && anyFocusActive;

  return (
    <g style={{ opacity }}>
      <path
        d={d}
        fill="none"
        stroke="transparent"
        strokeWidth={18}
        tabIndex={0}
        role="button"
        aria-label={`關聯 ${relSpec.label}：${relSpec.direction}`}
        style={{ cursor: 'pointer' }}
        onMouseEnter={onEnter}
        onMouseLeave={onLeave}
        onFocus={onEnter}
        onBlur={onLeave}
        onClick={onActivate}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            onActivate();
          }
        }}
      />
      <path
        d={d}
        fill="none"
        stroke={color}
        strokeWidth={strokeWidth}
        style={{ pointerEvents: 'none' }}
      />
      {[...manyGlyph.paths, ...oneGlyph.paths].map((glyph) => (
        <path key={glyph} d={glyph} fill="none" stroke={color} strokeWidth={1.5} style={{ pointerEvents: 'none' }} />
      ))}
      {manyGlyph.circle && (
        <circle
          cx={manyGlyph.circle.x}
          cy={manyGlyph.circle.y}
          r={4}
          strokeWidth={1.4}
          style={{ pointerEvents: 'none', fill: 'var(--dbe-canvas-bg)', stroke: color }}
        />
      )}
      {showLabel && (
        <g style={{ pointerEvents: 'none' }}>
          <rect x={label.x} y={label.y} width={label.w} height={label.h} rx={4} style={{ fill: 'var(--dbe-canvas-bg)' }} />
          <text
            x={label.anchorX}
            y={label.y + 10.5}
            textAnchor={label.textAnchor}
            fontSize={10}
            fontFamily="var(--dbe-font-mono)"
            style={{ fill: color }}
          >
            {relSpec.label}
          </text>
        </g>
      )}
    </g>
  );
}

// ---------------------------------------------------------------------------
// 子元件：欄位徽章
// ---------------------------------------------------------------------------

function ColumnBadge({ x, y, text }: { x: number; y: number; text: 'PK' | 'FK' | 'NN' }) {
  const w = badgeWidth(text);
  const bg = text === 'PK' ? 'var(--dbe-badge-pk-bg)' : text === 'FK' ? 'var(--dbe-badge-fk-bg)' : 'var(--dbe-badge-nn-bg)';
  const fg =
    text === 'PK' ? 'var(--dbe-badge-pk-text)' : text === 'FK' ? 'var(--dbe-badge-fk-text)' : 'var(--dbe-badge-nn-text)';
  return (
    <g>
      <rect x={x} y={y} width={w} height={14} rx={4} style={{ fill: bg }} />
      <text x={x + w / 2} y={y + 10.5} textAnchor="middle" fontSize={9} fontFamily="var(--dbe-font-mono)" style={{ fill: fg }}>
        {text}
      </text>
    </g>
  );
}

// ---------------------------------------------------------------------------
// 子元件：資料表卡片
// ---------------------------------------------------------------------------

interface TableCardProps {
  table: TableSpec;
  level: Level;
  collapsed: boolean;
  onToggleCollapse: () => void;
  isActiveTable: boolean;
  activeColumns: Set<string>;
  anyFocusActive: boolean;
  onEnterTable: () => void;
  onLeaveTable: () => void;
  onEnterColumn: (name: string) => void;
  onLeaveColumn: () => void;
  onActivateTable: () => void;
  onSelectColumn: (name: string) => void;
  onPointerDownHeader: (e: ReactPointerEvent<SVGRectElement>) => void;
  onPointerMoveHeader: (e: ReactPointerEvent<SVGRectElement>) => void;
  onPointerUpHeader: (e: ReactPointerEvent<SVGRectElement>) => void;
  dragging: boolean;
  position: { x: number; y: number };
  cardNodeRef: (el: SVGGElement | null) => void;
  noteOpen: boolean;
  noteHovered: boolean;
  onNoteToggle: () => void;
  onNoteEnter: () => void;
  onNoteLeave: () => void;
}

function TableCard({
  table,
  level,
  collapsed,
  onToggleCollapse,
  isActiveTable,
  activeColumns,
  anyFocusActive,
  onEnterTable,
  onLeaveTable,
  onEnterColumn,
  onLeaveColumn,
  onActivateTable,
  onSelectColumn,
  onPointerDownHeader,
  onPointerMoveHeader,
  onPointerUpHeader,
  dragging,
  position,
  cardNodeRef,
  noteOpen,
  noteHovered,
  onNoteToggle,
  onNoteEnter,
  onNoteLeave,
}: TableCardProps) {
  const width = TABLE_WIDTHS[table.id];
  const cols = visibleColumns(table, level, collapsed ? new Set([table.id]) : new Set());
  const height = HEADER_HEIGHT + cols.length * ROW_HEIGHT;
  const expandDisabled = level !== 'all';
  const expandAriaLabel = expandDisabled
    ? level === 'tables'
      ? `${table.name}：目前為「僅資料表」層級，無法個別展開`
      : `${table.name}：目前為「僅鍵值」層級，無法個別展開`
    : collapsed
      ? `展開 ${table.name} 的全部欄位`
      : `收合 ${table.name}，只顯示鍵值欄位`;
  const borderColor = isActiveTable ? 'var(--dbe-primary)' : 'var(--dbe-border)';
  const borderWidth = isActiveTable ? 2 : 1;
  const cardOpacity = anyFocusActive && !isActiveTable ? 0.35 : 1;

  return (
    <g
      ref={cardNodeRef}
      style={{ opacity: cardOpacity }}
      tabIndex={0}
      role="group"
      aria-label={`資料表 ${table.name}，${table.columns.length} 個欄位`}
      onMouseEnter={onEnterTable}
      onMouseLeave={onLeaveTable}
      onFocus={(e) => {
        if (e.target === e.currentTarget) onEnterTable();
      }}
      onBlur={(e) => {
        if (e.target === e.currentTarget) onLeaveTable();
      }}
      onClick={onActivateTable}
      onKeyDown={(e) => {
        if (e.target !== e.currentTarget) return;
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onActivateTable();
        }
      }}
    >
      <rect x={position.x} y={position.y} width={width} height={height} rx={CARD_RADIUS} style={{ fill: 'var(--dbe-surface)' }} />
      <path
        d={`M ${position.x} ${position.y + CARD_RADIUS} a ${CARD_RADIUS} ${CARD_RADIUS} 0 0 1 ${CARD_RADIUS} -${CARD_RADIUS} h ${
          width - CARD_RADIUS * 2
        } a ${CARD_RADIUS} ${CARD_RADIUS} 0 0 1 ${CARD_RADIUS} ${CARD_RADIUS} v ${HEADER_HEIGHT - CARD_RADIUS} h ${-width} z`}
        style={{ fill: 'var(--dbe-header-bg)' }}
      />
      <rect
        x={position.x}
        y={position.y}
        width={width}
        height={height}
        rx={CARD_RADIUS}
        fill="none"
        stroke={borderColor}
        strokeWidth={borderWidth}
      />

      <text
        x={position.x + 14}
        y={position.y + 23}
        fontSize={13}
        fontWeight={700}
        fontFamily="var(--dbe-font-mono)"
        style={{ fill: 'var(--dbe-header-text)' }}
      >
        {table.name}
      </text>

      {/* 拖曳把手：整個表頭皆可拖曳；stopPropagation 避免同時觸發畫布平移 */}
      <rect
        x={position.x}
        y={position.y}
        width={width - 28}
        height={HEADER_HEIGHT}
        fill="transparent"
        style={{ cursor: dragging ? 'grabbing' : 'grab' }}
        onPointerDown={onPointerDownHeader}
        onPointerMove={onPointerMoveHeader}
        onPointerUp={onPointerUpHeader}
      />

      <foreignObject x={position.x + width - 30} y={position.y + 6} width={24} height={24}>
        <button
          type="button"
          className="dbe-expand-btn"
          aria-expanded={!collapsed}
          aria-label={expandAriaLabel}
          disabled={expandDisabled}
          onClick={(e) => {
            e.stopPropagation();
            onToggleCollapse();
          }}
        >
          {collapsed ? <ChevronRight size={14} /> : <ChevronDown size={14} />}
        </button>
      </foreignObject>

      {cols.map((col, idx) => {
        const rowTop = position.y + HEADER_HEIGHT + idx * ROW_HEIGHT;
        const badges = columnBadges(table.id, col);
        const keyish = isKeyColumn(table.id, col.name);
        const columnKey = `${table.id}.${col.name}`;
        const isColActive = activeColumns.has(columnKey);
        const nameX = position.x + ROW_PAD_X;
        let badgeX = nameX + col.name.length * CHAR_W + BADGE_GAP;
        const isBodyNote = table.id === 'posts' && col.name === 'body' && col.note;

        return (
          <g
            key={col.name}
            onMouseEnter={() => onEnterColumn(col.name)}
            onMouseLeave={onLeaveColumn}
            {...(keyish
              ? {
                  tabIndex: 0,
                  role: 'button',
                  'aria-label': `欄位 ${table.name}.${col.name}，${badges.join('、')}`,
                  onFocus: () => onEnterColumn(col.name),
                  onBlur: onLeaveColumn,
                  onClick: (e: React.MouseEvent) => {
                    e.stopPropagation();
                    onSelectColumn(col.name);
                  },
                  onKeyDown: (e: ReactKeyboardEvent<SVGGElement>) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      e.stopPropagation();
                      onSelectColumn(col.name);
                    }
                  },
                }
              : {})}
          >
            {isColActive && (
              <rect x={position.x + 2} y={rowTop} width={width - 4} height={ROW_HEIGHT} style={{ fill: 'var(--dbe-primary-soft-bg)' }} />
            )}
            {keyish && <KeyRound x={nameX - 2} y={rowTop + 6} size={0} />}
            <text
              x={nameX}
              y={rowTop + 18}
              fontSize={12}
              fontWeight={keyish ? 700 : 500}
              fontFamily="var(--dbe-font-mono)"
              style={{ fill: 'var(--dbe-ink)' }}
            >
              {col.name}
            </text>
            {badges.map((b) => {
              const bx = badgeX;
              badgeX += badgeWidth(b) + BADGE_GAP;
              return <ColumnBadge key={b} x={bx} y={rowTop + 7} text={b} />;
            })}
            <text
              x={position.x + width - ROW_PAD_X}
              y={rowTop + 18}
              textAnchor="end"
              fontSize={11}
              fontFamily="var(--dbe-font-mono)"
              style={{ fill: 'var(--dbe-text-soft)' }}
            >
              {col.type}
            </text>
            {isBodyNote && (
              <foreignObject x={position.x + width - ROW_PAD_X - 60} y={rowTop + 4} width={20} height={20}>
                <span className="dbe-tooltip-wrap">
                  <button
                    type="button"
                    className="dbe-note-btn"
                    aria-label={`備註：${col.note}`}
                    aria-expanded={noteOpen || noteHovered}
                    onClick={(e) => {
                      e.stopPropagation();
                      onNoteToggle();
                    }}
                    onMouseEnter={onNoteEnter}
                    onMouseLeave={onNoteLeave}
                    onFocus={onNoteEnter}
                    onBlur={onNoteLeave}
                    onKeyDown={(e) => {
                      if (e.key === 'Escape' && (noteOpen || noteHovered)) {
                        e.stopPropagation();
                        if (noteOpen) onNoteToggle();
                        onNoteLeave();
                      }
                    }}
                  >
                    <StickyNote size={13} />
                  </button>
                </span>
              </foreignObject>
            )}
          </g>
        );
      })}
    </g>
  );
}

// ---------------------------------------------------------------------------
// 子元件：詳細面板
// ---------------------------------------------------------------------------

function DetailPanel({
  table,
  reduced,
  onClose,
  panelRef,
}: {
  table: TableSpec;
  reduced: boolean;
  onClose: () => void;
  panelRef: React.RefObject<HTMLDivElement>;
}) {
  const records = RECORDS[table.id];
  return (
    <motion.div
      key={table.id}
      ref={panelRef}
      className="dbe-panel"
      role="dialog"
      aria-modal="false"
      aria-label={`${table.name} 範例資料`}
      tabIndex={-1}
      initial={reduced ? { opacity: 0 } : { opacity: 0, x: 16 }}
      animate={{ opacity: 1, x: 0 }}
      exit={reduced ? { opacity: 0 } : { opacity: 0, x: 16 }}
      transition={{ duration: reduced ? 0.12 : 0.2, ease: 'easeOut' }}
    >
      <div className="dbe-panel-header">
        <span className="dbe-panel-title">{table.name}</span>
        <button type="button" className="dbe-panel-close" aria-label="關閉範例資料" onClick={onClose}>
          <X size={16} />
        </button>
      </div>
      <div className="dbe-panel-body">
        <table className="dbe-table">
          <thead>
            <tr>
              {table.columns.map((col) => (
                <th key={col.name}>{col.name}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {records.map((row, i) => (
              <tr key={i}>
                {table.columns.map((col) => {
                  const value = row[col.name];
                  return (
                    <td key={col.name} className={value === undefined ? 'dbe-empty' : undefined}>
                      {value === undefined ? '—' : String(value)}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </motion.div>
  );
}

// ---------------------------------------------------------------------------
// 根元件
// ---------------------------------------------------------------------------

interface ViewState {
  x: number;
  y: number;
  k: number;
}

function computeFitView(
  positions: PositionMap,
  level: Level,
  collapsed: Set<TableId>,
  containerW: number,
  containerH: number
): ViewState {
  const rects: Rect[] = TABLES.map((t) => getTableRect(t, positions, level, collapsed));
  for (const relSpec of REFS) {
    const points = buildRoute(
      relSpec.many.table,
      relSpec.many.column,
      relSpec.one.table,
      relSpec.one.column,
      positions,
      level,
      collapsed,
      relSpec.channelOffset
    );
    if (points.length === 0) continue;
    for (const pt of points) rects.push({ x: pt.x - 20, y: pt.y - 8, w: 40, h: 16 });
    rects.push(routeLabelBox(points, relSpec));
  }
  const minX = Math.min(...rects.map((r) => r.x));
  const minY = Math.min(...rects.map((r) => r.y));
  const maxX = Math.max(...rects.map((r) => r.x + r.w));
  const maxY = Math.max(...rects.map((r) => r.y + r.h));
  const contentW = Math.max(maxX - minX, 1);
  const contentH = Math.max(maxY - minY, 1);
  const padding = 48;
  const safeW = Math.max(containerW, 1);
  const safeH = Math.max(containerH, 1);
  const scaleX = (safeW - padding * 2) / contentW;
  const scaleY = (safeH - padding * 2) / contentH;
  const k = clamp(Math.min(scaleX, scaleY), MIN_K, MAX_K);
  const cx = minX + contentW / 2;
  const cy = minY + contentH / 2;
  return { x: safeW / 2 - cx * k, y: safeH / 2 - cy * k, k };
}

interface CardDragOrigin {
  pointerId: number;
  clientX: number;
  clientY: number;
  startX: number;
  startY: number;
  k: number;
}
interface PanOrigin {
  pointerId: number;
  clientX: number;
  clientY: number;
  startX: number;
  startY: number;
}

export default function DbmlSampleInteractiveErd() {
  const reduced = Boolean(useReducedMotion());
  const [positions, setPositions] = useState<PositionMap>(INITIAL_POSITIONS);
  const [level, setLevel] = useState<Level>('all');
  const [collapsed, setCollapsed] = useState<Set<TableId>>(new Set());
  const [view, setView] = useState<ViewState>({ x: 0, y: 0, k: 1 });
  const [hoverFocus, setHoverFocus] = useState<FocusState | null>(null);
  const [selectedFocus, setSelectedFocus] = useState<FocusState | null>(null);
  const [panelTable, setPanelTable] = useState<TableId | null>(null);
  const [dragTableId, setDragTableId] = useState<TableId | null>(null);
  const [noteOpen, setNoteOpen] = useState(false);
  const [noteHovered, setNoteHovered] = useState(false);
  const [liveMessage, setLiveMessage] = useState('');

  const canvasRef = useRef<HTMLDivElement>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const cardDragRef = useRef<CardDragOrigin | null>(null);
  // 拖曳標頭後放開仍會觸發 click；位移超過門檻就吞掉這次開面板。
  const justDraggedRef = useRef(false);
  const panRef = useRef<PanOrigin | null>(null);
  const justPannedRef = useRef(false);
  const cardNodeRefs = useRef<Record<TableId, SVGGElement | null>>({ users: null, posts: null, follows: null });
  const didFitOnMount = useRef(false);

  const announce = (msg: string) => setLiveMessage(msg);

  const effectiveFocus = hoverFocus ?? selectedFocus;
  const active = useMemo(() => computeActiveSet(effectiveFocus), [effectiveFocus]);
  const anyFocusActive = effectiveFocus !== null;
  const chipText = statusChipText(effectiveFocus);

  // 備註顯示在固定狀態列（不疊在畫布上，避免遮住鄰列文字）；body 列被隱藏時不顯示。
  const noteText =
    (noteOpen || noteHovered) && visibleColumns(TABLES_BY_ID.posts, level, collapsed).some((c) => c.name === 'body')
      ? TABLES_BY_ID.posts.columns.find((c) => c.name === 'body')?.note ?? null
      : null;
  const stripText = noteText ? `posts.body 備註：${noteText}` : chipText;

  useEffect(() => {
    if (didFitOnMount.current) return;
    const el = canvasRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    if (rect.width > 0 && rect.height > 0) {
      didFitOnMount.current = true;
      setView(computeFitView(INITIAL_POSITIONS, 'all', new Set(), rect.width, rect.height));
    }
  }, []);

  useEffect(() => {
    const el = canvasRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      const rect = el.getBoundingClientRect();
      const mouseX = e.clientX - rect.left;
      const mouseY = e.clientY - rect.top;
      setView((prev) => {
        const factor = Math.exp(-e.deltaY * 0.0012);
        const nextK = clamp(prev.k * factor, MIN_K, MAX_K);
        const worldX = (mouseX - prev.x) / prev.k;
        const worldY = (mouseY - prev.y) / prev.k;
        return { x: mouseX - worldX * nextK, y: mouseY - worldY * nextK, k: nextK };
      });
    };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, []);

  useEffect(() => {
    if (panelTable && panelRef.current) {
      panelRef.current.focus();
    }
  }, [panelTable]);

  function closePanel() {
    const tableId = panelTable;
    setPanelTable(null);
    announce('已關閉範例資料面板');
    if (tableId) {
      cardNodeRefs.current[tableId]?.focus();
    }
  }

  function handleRootKeyDown(e: ReactKeyboardEvent<HTMLDivElement>) {
    if (e.key !== 'Escape') return;
    if (noteOpen) {
      setNoteOpen(false);
      return;
    }
    if (panelTable) {
      closePanel();
      return;
    }
    if (selectedFocus) {
      setSelectedFocus(null);
      announce('已清除選取');
    }
  }

  function handleSetLevel(next: Level) {
    setLevel(next);
    if (next === 'all') setCollapsed(new Set());
    announce(`顯示層級：${LEVEL_LABELS[next]}`);
  }
  function handleExpandAll() {
    setCollapsed(new Set());
    announce('已全部展開');
  }
  function handleCollapseAll() {
    setCollapsed(new Set(TABLES.map((t) => t.id)));
    announce('已全部收合');
  }
  function handleToggleCollapse(tableId: TableId) {
    if (level !== 'all') return;
    const wasCollapsed = collapsed.has(tableId);
    setCollapsed((prev) => {
      const next = new Set(prev);
      if (next.has(tableId)) next.delete(tableId);
      else next.add(tableId);
      return next;
    });
    announce(`${tableId} ${wasCollapsed ? '已展開' : '已收合'}`);
  }

  function handleActivateTable(tableId: TableId) {
    if (justDraggedRef.current) {
      justDraggedRef.current = false;
      return;
    }
    setSelectedFocus({ kind: 'table', id: tableId });
    setPanelTable(tableId);
    announce(`已開啟 ${tableId} 的範例資料面板`);
  }
  function handleSelectColumn(tableId: TableId, columnName: string) {
    setSelectedFocus({ kind: 'column', id: `${tableId}.${columnName}` });
  }
  function handleActivateRef(refId: string) {
    setSelectedFocus({ kind: 'ref', id: refId });
  }

  function zoomByFactor(factor: number) {
    const el = canvasRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const cx = rect.width / 2;
    const cy = rect.height / 2;
    setView((prev) => {
      const nextK = clamp(prev.k * factor, MIN_K, MAX_K);
      const worldX = (cx - prev.x) / prev.k;
      const worldY = (cy - prev.y) / prev.k;
      return { x: cx - worldX * nextK, y: cy - worldY * nextK, k: nextK };
    });
  }
  function handleFitToContent() {
    const el = canvasRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    setView(computeFitView(positions, level, collapsed, rect.width, rect.height));
  }
  function handleReset() {
    setPositions(INITIAL_POSITIONS);
    setLevel('all');
    setCollapsed(new Set());
    setSelectedFocus(null);
    setHoverFocus(null);
    setPanelTable(null);
    const el = canvasRef.current;
    if (el) {
      const rect = el.getBoundingClientRect();
      setView(computeFitView(INITIAL_POSITIONS, 'all', new Set(), rect.width, rect.height));
    }
    announce('已重設檢視');
  }

  function handleCardPointerDown(tableId: TableId) {
    return (e: ReactPointerEvent<SVGRectElement>) => {
      e.stopPropagation();
      e.currentTarget.setPointerCapture(e.pointerId);
      cardDragRef.current = {
        pointerId: e.pointerId,
        clientX: e.clientX,
        clientY: e.clientY,
        startX: positions[tableId].x,
        startY: positions[tableId].y,
        k: view.k,
      };
      justDraggedRef.current = false;
      setDragTableId(tableId);
    };
  }
  function handleCardPointerMove(tableId: TableId) {
    return (e: ReactPointerEvent<SVGRectElement>) => {
      const origin = cardDragRef.current;
      if (!origin || origin.pointerId !== e.pointerId) return;
      e.stopPropagation();
      if (Math.abs(e.clientX - origin.clientX) > 3 || Math.abs(e.clientY - origin.clientY) > 3) justDraggedRef.current = true;
      const dx = (e.clientX - origin.clientX) / origin.k;
      const dy = (e.clientY - origin.clientY) / origin.k;
      setPositions((prev) => ({ ...prev, [tableId]: { x: origin.startX + dx, y: origin.startY + dy } }));
    };
  }
  function handleCardPointerUp() {
    return (e: ReactPointerEvent<SVGRectElement>) => {
      e.stopPropagation();
      const origin = cardDragRef.current;
      if (origin && e.currentTarget.hasPointerCapture(origin.pointerId)) {
        e.currentTarget.releasePointerCapture(origin.pointerId);
      }
      cardDragRef.current = null;
      setDragTableId(null);
    };
  }

  function handleCanvasPointerDown(e: ReactPointerEvent<SVGRectElement>) {
    e.currentTarget.setPointerCapture(e.pointerId);
    justPannedRef.current = false;
    panRef.current = { pointerId: e.pointerId, clientX: e.clientX, clientY: e.clientY, startX: view.x, startY: view.y };
  }
  function handleCanvasPointerMove(e: ReactPointerEvent<SVGRectElement>) {
    const origin = panRef.current;
    if (!origin || origin.pointerId !== e.pointerId) return;
    const dx = e.clientX - origin.clientX;
    const dy = e.clientY - origin.clientY;
    if (Math.abs(dx) > 3 || Math.abs(dy) > 3) justPannedRef.current = true;
    setView((prev) => ({ ...prev, x: origin.startX + dx, y: origin.startY + dy }));
  }
  function handleCanvasPointerUp(e: ReactPointerEvent<SVGRectElement>) {
    const origin = panRef.current;
    if (origin && e.currentTarget.hasPointerCapture(origin.pointerId)) {
      e.currentTarget.releasePointerCapture(origin.pointerId);
    }
    panRef.current = null;
  }
  function handleCanvasClick() {
    if (justPannedRef.current) {
      justPannedRef.current = false;
      return;
    }
    setSelectedFocus(null);
  }

  const panelTableSpec = panelTable ? TABLES_BY_ID[panelTable] : null;

  return (
    <div className="dbe-root not-prose" onKeyDown={handleRootKeyDown}>
      <style dangerouslySetInnerHTML={{ __html: SCOPED_CSS }} />

      <div className="dbe-toolbar">
        <div className="dbe-seg" role="radiogroup" aria-label="顯示層級">
          {(['all', 'keys', 'tables'] as Level[]).map((lv) => (
            <button
              key={lv}
              type="button"
              className="dbe-seg-btn"
              role="radio"
              aria-checked={level === lv}
              aria-pressed={level === lv}
              onClick={() => handleSetLevel(lv)}
            >
              {LEVEL_LABELS[lv]}
            </button>
          ))}
        </div>
        <button type="button" className="dbe-btn" onClick={handleExpandAll}>
          全部展開
        </button>
        <button type="button" className="dbe-btn" onClick={handleCollapseAll}>
          全部收合
        </button>
        <div className="dbe-spacer" />
        <button type="button" className="dbe-btn" aria-label="放大" onClick={() => zoomByFactor(1.25)}>
          <ZoomIn size={14} />
          放大
        </button>
        <button type="button" className="dbe-btn" aria-label="縮小" onClick={() => zoomByFactor(0.8)}>
          <ZoomOut size={14} />
          縮小
        </button>
        <button type="button" className="dbe-btn" aria-label="適合畫面" onClick={handleFitToContent}>
          <Maximize size={14} />
          適合畫面
        </button>
        <button type="button" className="dbe-btn" aria-label="重設" onClick={handleReset}>
          <RotateCcw size={14} />
          重設
        </button>
      </div>

      <div className={`dbe-chip${stripText ? '' : ' dbe-chip-idle'}`} aria-hidden="true">
        {noteText ? (
          <span role="tooltip" id="dbe-note-tip">{stripText}</span>
        ) : (
          stripText ?? '將游標移到資料表、欄位或關聯線上（或以 Tab 聚焦）查看關聯'
        )}
      </div>

      <div className="dbe-canvas-wrap" ref={canvasRef}>

        <svg width="100%" height="100%" style={{ display: 'block' }} role="img" aria-label="dbdiagram 範例 schema 的互動式 ERD：users、posts、follows 三張表">
          <rect
            x={0}
            y={0}
            width="100%"
            height="100%"
            fill="transparent"
            onPointerDown={handleCanvasPointerDown}
            onPointerMove={handleCanvasPointerMove}
            onPointerUp={handleCanvasPointerUp}
            onClick={handleCanvasClick}
          />
          <g transform={`translate(${view.x} ${view.y}) scale(${view.k})`}>
            <rect x={-4000} y={-4000} width={8000} height={8000} fill="url(#dbe-dot-pattern)" style={{ pointerEvents: 'none' }} />
            <defs>
              <pattern id="dbe-dot-pattern" width={22} height={22} patternUnits="userSpaceOnUse">
                <circle cx={2} cy={2} r={1.1} style={{ fill: 'var(--dbe-dot)' }} />
              </pattern>
            </defs>

            {REFS.map((ref) => (
              <RelationLine
                key={ref.id}
                relation={ref}
                positions={positions}
                level={level}
                collapsed={collapsed}
                active={active.refs.has(ref.id)}
                anyFocusActive={anyFocusActive}
                onEnter={() => setHoverFocus({ kind: 'ref', id: ref.id })}
                onLeave={() => setHoverFocus(null)}
                onActivate={() => handleActivateRef(ref.id)}
              />
            ))}

            {TABLES.map((table) => (
              <TableCard
                key={table.id}
                table={table}
                level={level}
                collapsed={collapsed.has(table.id)}
                onToggleCollapse={() => handleToggleCollapse(table.id)}
                isActiveTable={active.tables.has(table.id) && anyFocusActive}
                activeColumns={active.columns}
                anyFocusActive={anyFocusActive}
                onEnterTable={() => setHoverFocus({ kind: 'table', id: table.id })}
                onLeaveTable={() => setHoverFocus(null)}
                onEnterColumn={(name) => setHoverFocus({ kind: 'column', id: `${table.id}.${name}` })}
                onLeaveColumn={() => setHoverFocus(null)}
                onActivateTable={() => handleActivateTable(table.id)}
                onSelectColumn={(name) => handleSelectColumn(table.id, name)}
                onPointerDownHeader={handleCardPointerDown(table.id)}
                onPointerMoveHeader={handleCardPointerMove(table.id)}
                onPointerUpHeader={handleCardPointerUp()}
                dragging={dragTableId === table.id}
                position={positions[table.id]}
                cardNodeRef={(el) => {
                  cardNodeRefs.current[table.id] = el;
                }}
                noteOpen={table.id === 'posts' && noteOpen}
                noteHovered={table.id === 'posts' && noteHovered}
                onNoteToggle={() => setNoteOpen((v) => !v)}
                onNoteEnter={() => setNoteHovered(true)}
                onNoteLeave={() => setNoteHovered(false)}
              />
            ))}

          </g>
        </svg>

        <AnimatePresence>
          {panelTableSpec && <DetailPanel table={panelTableSpec} reduced={reduced} onClose={closePanel} panelRef={panelRef} />}
        </AnimatePresence>
      </div>

      <div className="dbe-live" role="status" aria-live="polite">
        {liveMessage}
      </div>
    </div>
  );
}
