// 本檔為 generated view——請勿手動編輯
// Generated by NoteCraft @ai-visualize (content-visualize skill); regenerate from the marker in specs/annotation/015-annotation-workspace/diagrams.mdx.

import { useState, type KeyboardEvent, type ReactNode } from 'react';
import { motion, AnimatePresence, useReducedMotion } from 'motion/react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from 'recharts';
import { Ban, Eye, ArrowRight } from 'lucide-react';
import clsx from 'clsx';

// ---------------------------------------------------------------------------
// SCOPED_CSS —— NoteCraft 的 tailwind content glob 是相對於它自己的安裝目錄
// （~/.notecraft/app-0.5.1/tailwind.config.mjs: "./src/**/*"），生成元件落在
// <repo>/.notecraft/components/ 不在掃描範圍內，JIT 從未看過這些 class，
// 實測絕大多數 class 對不到任何規則（p-4 → padding:0、text-xs → 18px）。
// 故本元件自帶所用到的 utility，全部限定在 .rfdr-root 底下，不依賴宿主 CSS。
// ---------------------------------------------------------------------------

const SCOPED_CSS = `
.rfdr-root { font-size: 0.875rem; line-height: 1.5; color: #334155; }
.rfdr-root p, .rfdr-root ul, .rfdr-root ol, .rfdr-root li { margin: 0; }
.rfdr-root button { font: inherit; color: inherit; background: none; border: 0; }
.rfdr-root textarea { font: inherit; color: inherit; background: #FFFFFF; }

.rfdr-root .flex { display: flex; }
.rfdr-root .inline-flex { display: inline-flex; }
.rfdr-root .grid { display: grid; }
.rfdr-root .block { display: block; }
.rfdr-root .grid-cols-1 { grid-template-columns: repeat(1, minmax(0, 1fr)); }
.rfdr-root .items-center { align-items: center; }
.rfdr-root .justify-between { justify-content: space-between; }
.rfdr-root .flex-wrap { flex-wrap: wrap; }
.rfdr-root .shrink-0 { flex-shrink: 0; }
.rfdr-root .w-full { width: 100%; }

.rfdr-root .gap-1 { gap: 0.25rem; }
.rfdr-root .gap-1\\.5 { gap: 0.375rem; }
.rfdr-root .gap-2 { gap: 0.5rem; }
.rfdr-root .gap-2\\.5 { gap: 0.625rem; }
.rfdr-root .gap-4 { gap: 1rem; }
.rfdr-root .p-1 { padding: 0.25rem; }
.rfdr-root .p-3 { padding: 0.75rem; }
.rfdr-root .p-4 { padding: 1rem; }
.rfdr-root .px-2\\.5 { padding-left: 0.625rem; padding-right: 0.625rem; }
.rfdr-root .px-3 { padding-left: 0.75rem; padding-right: 0.75rem; }
.rfdr-root .px-3\\.5 { padding-left: 0.875rem; padding-right: 0.875rem; }
.rfdr-root .py-1\\.5 { padding-top: 0.375rem; padding-bottom: 0.375rem; }
.rfdr-root .pt-3 { padding-top: 0.75rem; }
.rfdr-root .mb-1 { margin-bottom: 0.25rem; }
.rfdr-root .mb-2 { margin-bottom: 0.5rem; }
.rfdr-root .mt-0\\.5 { margin-top: 0.125rem; }
.rfdr-root .mt-1 { margin-top: 0.25rem; }
.rfdr-root .mt-3 { margin-top: 0.75rem; }
.rfdr-root .space-y-1 > * + * { margin-top: 0.25rem; }
.rfdr-root .space-y-3 > * + * { margin-top: 0.75rem; }
.rfdr-root .space-y-4 > * + * { margin-top: 1rem; }
.rfdr-root .space-y-5 > * + * { margin-top: 1.25rem; }

.rfdr-root .border { border-width: 1px; border-style: solid; border-color: #E2E8F0; }
.rfdr-root .border-t { border-top-width: 1px; border-top-style: solid; border-top-color: #E2E8F0; }
.rfdr-root .rounded-lg { border-radius: 0.5rem; }
.rfdr-root .border-slate-100 { border-color: #F1F5F9; }
.rfdr-root .border-slate-200 { border-color: #E2E8F0; }
.rfdr-root .border-indigo-500 { border-color: #6366F1; }
.rfdr-root .border-emerald-200 { border-color: #A7F3D0; }
.rfdr-root .border-emerald-500 { border-color: #10B981; }

.rfdr-root .bg-white { background-color: #FFFFFF; }
.rfdr-root .bg-slate-50 { background-color: #F8FAFC; }
.rfdr-root .bg-indigo-50 { background-color: #EEF2FF; }
.rfdr-root .bg-indigo-600 { background-color: #4F46E5; }
.rfdr-root .bg-emerald-50 { background-color: #ECFDF5; }

.rfdr-root .text-xs { font-size: 0.75rem; line-height: 1rem; }
.rfdr-root .text-sm { font-size: 0.875rem; line-height: 1.25rem; }
.rfdr-root .text-4xl { font-size: 2.25rem; line-height: 2.5rem; }
.rfdr-root .font-medium { font-weight: 500; }
.rfdr-root .font-semibold { font-weight: 600; }
.rfdr-root .font-bold { font-weight: 700; }
.rfdr-root .text-white { color: #FFFFFF; }
.rfdr-root .text-slate-400 { color: #94A3B8; }
.rfdr-root .text-slate-500 { color: #64748B; }
.rfdr-root .text-slate-600 { color: #475569; }
.rfdr-root .text-slate-700 { color: #334155; }
.rfdr-root .text-slate-800 { color: #1E293B; }
.rfdr-root .text-indigo-600 { color: #4F46E5; }
.rfdr-root .text-emerald-700 { color: #047857; }
.rfdr-root .text-emerald-800 { color: #065F46; }

.rfdr-root .cursor-default { cursor: default; }
.rfdr-root .cursor-not-allowed { cursor: not-allowed; }
.rfdr-root .transition-colors { transition: color 150ms, background-color 150ms, border-color 150ms; }
.rfdr-root button:disabled { cursor: not-allowed; opacity: 0.4; }
.rfdr-root button:disabled.bg-indigo-600 { background-color: #E2E8F0; color: #94A3B8; opacity: 1; }
.rfdr-root [role="button"] { cursor: pointer; }

@media (min-width: 768px) {
  .rfdr-root .md\\:grid-cols-2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}
@media (prefers-reduced-motion: reduce) {
  .rfdr-root .transition-colors { transition: none; }
}
`;

// ---------------------------------------------------------------------------
// Domain types
// ---------------------------------------------------------------------------

type ScaleMode = 'single' | 'batch';
type ReviewDecision = 'approve' | 'modify' | 'bypass';
type ArbitrationOutcome = 'adopt_a' | 'adopt_b' | 'reject';
type ExceptionAction = 'adopt_annotator' | 'adopt_reviewer' | 'exclude_from_dataset';
type BatchJudgment = 'acceptable' | 'unacceptable';

interface SingleFlowState {
  step: number; // 0..7，僅能在 computeVisiblePath 已解鎖的步驟之間移動
  decision: ReviewDecision | null;
  arbitration: ArbitrationOutcome | null;
  exceptionAction: ExceptionAction | null;
  exceptionReason: string;
  // 規劃書 SingleFlowState 未列出此欄位；用來標記「例外池已按下確認收尾」，
  // 是 computeVisiblePath 判斷步驟 7 是否解鎖所需的最小狀態，見交付報告的偏離說明。
  exceptionConfirmed: boolean;
  // 一旦走到步驟 7 即為已定稿：往回瀏覽仍可，但所有決定鎖定，只能重新示範。
  finalized: boolean;
}

const INITIAL_SINGLE_STATE: SingleFlowState = {
  step: 0,
  decision: null,
  arbitration: null,
  exceptionAction: null,
  exceptionReason: '',
  exceptionConfirmed: false,
  finalized: false,
};

const DECISION_LABEL: Record<ReviewDecision, string> = {
  approve: '通過',
  modify: '修正',
  bypass: '無法判定',
};

const ARBITRATION_LABEL: Record<ArbitrationOutcome, string> = {
  adopt_a: '採原答案',
  adopt_b: '採審核員值',
  reject: '兩者皆非',
};

const EXCEPTION_LABEL: Record<ExceptionAction, string> = {
  adopt_annotator: '採納標記員',
  adopt_reviewer: '採納審核員',
  exclude_from_dataset: '排除資料集',
};

interface StepDef {
  label: string;
  detail: string;
}

// 步驟 0 是送出前（尚未成立審核單位，圖上沒有對應節點）；其餘編號即流程圖上的節點：1 送出、2 逐份審核、3 做決定、4 爭議池、
// 5 仲裁、6 例外池／負責人、7 已定稿。標題沿用 diagrams/review-flow-dry-run.html
// 節點上的文字，讓詳情面板與圖上讀到的字一致。
const STEP_DEFS: Record<number, StepDef> = {
  0: {
    label: '尚無標記提交',
    detail: '標記員送出前不成立審核單位，審核端只顯示「尚無標記提交」。按下一步模擬標記員送出。',
  },
  1: {
    label: '標記員送出試標',
    detail: '同一份資料由多位標記員各標一次，送出後成立審核單位。',
  },
  2: {
    label: '審核員逐份審核',
    detail: '以樣本為單位分配：同一份資料的所有標記交給同一位審核員，逐項比對、一次看完。',
  },
  3: {
    label: '審核員做決定',
    detail: '通過、直接改答案、標成無法判定三選一；按下送出審核之前都只是草稿。',
  },
  4: {
    label: '爭議池',
    detail: '改答案與無法判定都不會馬上生效，一律送進爭議池，還沒定稿、等待裁決。',
  },
  5: {
    label: '仲裁者逐項裁決',
    detail: '只能在標記員原答案與審核員答案之間二選一，不能自己寫第三種答案，也不退回重標。',
  },
  6: {
    label: '最終例外池',
    detail: '裁決者認為兩邊都不能用時要填理由，這一項落到最終例外池，由專案負責人逐筆處理。',
  },
  7: {
    label: '已定稿',
    detail: '只顯示文字、不能再修改；歷程記錄原答案 ➔ 審核員改 ➔ 仲裁採用的責任鏈。',
  },
};

/** 純函式：依決策與仲裁結果，算出目前已解鎖、可顯示的步驟路徑（遞增排序）。 */
function computeVisiblePath(
  decision: ReviewDecision | null,
  arbitration: ArbitrationOutcome | null,
  exceptionConfirmed: boolean,
): number[] {
  const path = [0, 1, 2, 3];
  if (decision === null) return path;
  // 通過直接走「通過」那條線到已定稿，不經過爭議池（步驟 4）。
  if (decision === 'approve') {
    path.push(7);
    return path;
  }
  path.push(4, 5);
  if (arbitration === null) return path;
  if (arbitration === 'reject') {
    path.push(6);
    if (exceptionConfirmed) path.push(7);
    return path;
  }
  path.push(7);
  return path;
}

/** 依 FR-094 責任鏈格式組出唯讀文字，僅在步驟 7 呼叫（此時必要欄位皆已就緒）。 */
function buildTraceString(state: SingleFlowState): string {
  if (state.decision === null) return '';
  const base = `歷程：標記 A → 審核 B（${DECISION_LABEL[state.decision]}）`;
  if (state.decision === 'approve' || state.arbitration === null) return base;
  const withArbitration = `${base} → 仲裁 C（${ARBITRATION_LABEL[state.arbitration]}）`;
  if (state.arbitration !== 'reject' || state.exceptionAction === null) return withArbitration;
  return `${withArbitration} → 例外池（${EXCEPTION_LABEL[state.exceptionAction]}）`;
}

function computeCanGoNext(state: SingleFlowState, path: number[]): boolean {
  const idx = path.indexOf(state.step);
  if (idx === -1 || idx === path.length - 1) return false;
  if (state.step === 3 && state.decision === null) return false;
  if (state.step === 5 && state.arbitration === null) return false;
  return true;
}

// ---------------------------------------------------------------------------
// 流程圖幾何 —— 節點座標、連線 d、線上說明的遮罩框與文字位置，全部逐字沿用
// specs/annotation/015-annotation-workspace/diagrams/review-flow-dry-run.html
// （viewBox 0 0 1200 1248）。互動只疊在這些圖形上，不另立版面。
// 生成元件的可用套件白名單沒有版面演算法（recharts 畫不了 node-link，d3-force
// 只會得到物理球團），要貼回原圖唯一的路是把座標當資料，故有下面兩張表。
// ---------------------------------------------------------------------------

const PAPER = '#F5F3FF';
const INK = '#1E1B4B';
const MUTED = '#64748B';
const SOFT = '#94A3B8';
const ACCENT = '#6366F1';
const MONO = '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace';

interface NodeSub {
  readonly text: string;
  readonly y: number;
  readonly soft?: boolean;
}

interface NodeDef {
  readonly id: string;
  /** 對應的步驟編號；null 代表這是說明性節點（原圖用虛線框），不可點。 */
  readonly step: number | null;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
  readonly rx: number;
  /** 菱形節點（審核員做決定）改用 polygon，rect 只當作選取外框的量尺。 */
  readonly points?: string;
  readonly cx: number;
  readonly fill: string;
  readonly stroke: string;
  readonly dash?: string;
  readonly title: string;
  readonly titleY: number;
  readonly subs: readonly NodeSub[];
}

interface EdgeLabel {
  readonly text: string;
  readonly x: number;
  readonly y: number;
  readonly anchor?: 'end';
  readonly size?: number;
}

interface EdgeDef {
  readonly id: string;
  readonly d: string;
  readonly soft?: boolean;
  readonly dash?: string;
  readonly box?: { readonly x: number; readonly y: number; readonly w: number; readonly h: number };
  readonly labels: readonly EdgeLabel[];
}

const SINGLE_NODES: readonly NodeDef[] = [
  {
    id: 'submit', step: 1, x: 304, y: 48, w: 192, h: 44, rx: 20, cx: 400,
    fill: '#FFFFFF', stroke: INK, title: '標記員送出試標', titleY: 66,
    subs: [{ text: '同一份資料多人各標一次', y: 81 }],
  },
  {
    id: 'assign', step: null, x: 64, y: 140, w: 216, h: 64, rx: 6, cx: 172,
    fill: 'rgba(30,27,75,0.03)', stroke: SOFT, dash: '4,3', title: '審核怎麼分配', titleY: 162,
    subs: [
      { text: '以樣本為單位 · 同一份資料的所有標記', y: 178 },
      { text: '交給同一位審核員', y: 192 },
    ],
  },
  {
    id: 'review', step: 2, x: 304, y: 140, w: 192, h: 52, rx: 6, cx: 400,
    fill: '#FFFFFF', stroke: INK, title: '審核員逐份審核', titleY: 162,
    subs: [{ text: '逐項比對 · 同一份資料一次看完', y: 179 }],
  },
  {
    id: 'decide', step: 3, x: 304, y: 256, w: 192, h: 88, rx: 6, cx: 400,
    points: '400,256 496,300 400,344 304,300',
    fill: '#FFFFFF', stroke: INK, title: '審核員做決定', titleY: 292,
    subs: [{ text: '通過／改答案／無法判定', y: 308 }],
  },
  {
    id: 'dispute', step: 4, x: 640, y: 272, w: 176, h: 56, rx: 6, cx: 728,
    fill: 'rgba(30,27,75,0.05)', stroke: MUTED, title: '爭議池', titleY: 296,
    subs: [{ text: '還沒定稿，等待裁決', y: 313 }],
  },
  {
    id: 'arbitrate', step: 5, x: 640, y: 392, w: 176, h: 64, rx: 6, cx: 728,
    fill: '#FFFFFF', stroke: INK, title: '仲裁者逐項裁決', titleY: 414,
    subs: [
      { text: '只能二選一，不能自己寫', y: 430 },
      { text: '須勾選為仲裁者且未參與這份', y: 444, soft: true },
    ],
  },
  {
    id: 'exception', step: 6, x: 640, y: 520, w: 176, h: 56, rx: 6, cx: 728,
    fill: '#FFFFFF', stroke: ACCENT, title: '最終例外池', titleY: 544,
    subs: [{ text: '入口在「標記進度」分頁', y: 561 }],
  },
  {
    id: 'owner', step: 6, x: 640, y: 640, w: 176, h: 64, rx: 6, cx: 728,
    fill: '#FFFFFF', stroke: INK, title: '專案負責人處理', titleY: 662,
    subs: [
      { text: '試標沒有自己填答案這個出口', y: 678 },
      { text: '只能採用其中一邊，或移除', y: 692, soft: true },
    ],
  },
  {
    id: 'finalized', step: 7, x: 304, y: 640, w: 192, h: 64, rx: 6, cx: 400,
    fill: '#EEF2FF', stroke: ACCENT, title: '已定稿', titleY: 664,
    subs: [
      { text: '只顯示文字，不能再修改', y: 680 },
      { text: '歷程：原答案 ➔ 審核員改 ➔ 仲裁採用', y: 694, soft: true },
    ],
  },
];

const SINGLE_EDGES: readonly EdgeDef[] = [
  {
    id: 'submit-review', d: 'M 400 92 V 140',
    box: { x: 408, y: 106, w: 52, h: 12 },
    labels: [{ text: '成立審核單位', x: 412, y: 115 }],
  },
  { id: 'assign-review', d: 'M 280 172 H 304', soft: true, dash: '4,3', labels: [] },
  {
    id: 'review-decide', d: 'M 400 224 V 256',
    box: { x: 408, y: 232, w: 52, h: 12 },
    labels: [{ text: '送出後才算數', x: 412, y: 241 }],
  },
  {
    id: 'decide-finalized', d: 'M 400 344 V 640',
    box: { x: 408, y: 360, w: 28, h: 12 },
    labels: [{ text: '通過', x: 412, y: 369 }],
  },
  {
    id: 'decide-dispute', d: 'M 496 300 H 640',
    box: { x: 504, y: 278, w: 120, h: 12 },
    labels: [{ text: '改答案或無法判定 → 爭議中', x: 508, y: 287 }],
  },
  {
    id: 'dispute-arbitrate', d: 'M 728 328 V 392',
    box: { x: 736, y: 348, w: 52, h: 12 },
    labels: [{ text: '逐項等待裁決', x: 740, y: 357 }],
  },
  {
    id: 'arbitrate-finalized',
    d: 'M 640 424 H 552 A 8 8 0 0 0 544 432 V 648 A 8 8 0 0 1 536 656 H 496',
    box: { x: 440, y: 520, w: 88, h: 12 },
    labels: [{ text: '採用其中一邊 → 定稿', x: 444, y: 529 }],
  },
  {
    id: 'arbitrate-exception', d: 'M 728 456 V 520',
    box: { x: 736, y: 480, w: 100, h: 12 },
    labels: [{ text: '兩邊都不能用 · 要填理由', x: 740, y: 489 }],
  },
  {
    id: 'exception-owner', d: 'M 728 576 V 640',
    box: { x: 736, y: 600, w: 36, h: 12 },
    labels: [{ text: '逐筆處理', x: 740, y: 609 }],
  },
  {
    id: 'owner-finalized', d: 'M 640 680 H 496',
    box: { x: 520, y: 686, w: 112, h: 12 },
    labels: [{ text: '採用原答案／採用審核員答案', x: 628, y: 695, anchor: 'end' }],
  },
  {
    id: 'owner-removed', d: 'M 816 672 H 856', soft: true, dash: '4,3',
    labels: [{ text: '從資料集移除', x: 864, y: 676, size: 9 }],
  },
];

const BATCH_NODES: readonly NodeDef[] = [
  {
    id: 'all-submitted', step: null, x: 64, y: 796, w: 192, h: 52, rx: 6, cx: 160,
    fill: '#FFFFFF', stroke: INK, title: '所有標記員都送出了', titleY: 818,
    subs: [{ text: '這一輪試標跑完', y: 835 }],
  },
  {
    id: 'pending-confirm', step: null, x: 312, y: 796, w: 192, h: 52, rx: 6, cx: 408,
    fill: 'rgba(30,27,75,0.05)', stroke: MUTED, title: '任務轉為待確認', titleY: 818,
    subs: [{ text: '由系統自動判斷', y: 835 }],
  },
  {
    id: 'raw-answers', step: null, x: 64, y: 890, w: 216, h: 52, rx: 6, cx: 172,
    fill: 'rgba(30,27,75,0.05)', stroke: MUTED, title: '標記員的原始答案', titleY: 912,
    subs: [{ text: '還沒被審核改過的版本', y: 929 }],
  },
  {
    id: 'consistency', step: null, x: 336, y: 890, w: 256, h: 52, rx: 6, cx: 464,
    fill: '#FFFFFF', stroke: INK, title: '標記一致性', titleY: 912,
    subs: [{ text: '標記員彼此之間有多一致', y: 929 }],
  },
  {
    id: 'settled-results', step: null, x: 64, y: 962, w: 216, h: 52, rx: 6, cx: 172,
    fill: 'rgba(30,27,75,0.05)', stroke: MUTED, title: '每一項的定案結果', titleY: 984,
    subs: [{ text: '通過／審核修正／仲裁裁定', y: 1001 }],
  },
  {
    id: 'modified-rate', step: null, x: 336, y: 962, w: 256, h: 52, rx: 6, cx: 464,
    fill: '#FFFFFF', stroke: INK, title: '標記員被修改的比例', titleY: 984,
    subs: [{ text: '每個人最後被改掉多少', y: 1001 }],
  },
  {
    id: 'owner-judges', step: null, x: 656, y: 890, w: 192, h: 124, rx: 6, cx: 752,
    fill: '#FFFFFF', stroke: INK, title: '由專案主持人判讀', titleY: 944,
    subs: [{ text: '系統不會自動判定合格', y: 961 }],
  },
  {
    id: 'open-official', step: null, x: 904, y: 890, w: 248, h: 52, rx: 6, cx: 1028,
    fill: '#EEF2FF', stroke: ACCENT, title: '開放正式標記', titleY: 912,
    subs: [{ text: '表示指引已經夠清楚', y: 929 }],
  },
  {
    id: 'revise-guideline', step: null, x: 904, y: 962, w: 248, h: 52, rx: 6, cx: 1028,
    fill: '#FFFFFF', stroke: INK, title: '修改指引後再跑一輪試標', titleY: 984,
    subs: [{ text: '改的是指引，不是退回個別樣本', y: 1001 }],
  },
  {
    id: 'history-feedback', step: null, x: 336, y: 1048, w: 256, h: 56, rx: 6, cx: 464,
    fill: 'rgba(30,27,75,0.03)', stroke: SOFT, dash: '4,3', title: '試標歷程回饋', titleY: 1072,
    subs: [{ text: '標記員看得到自己哪幾項被改、被誰定案', y: 1089 }],
  },
];

const BATCH_EDGES: readonly EdgeDef[] = [
  { id: 'submitted-pending', d: 'M 256 822 H 312', labels: [] },
  {
    id: 'raw-consistency', d: 'M 280 916 H 336',
    box: { x: 344, y: 898, w: 40, h: 12 },
    labels: [{ text: '統計出來', x: 348, y: 907 }],
  },
  { id: 'settled-rate', d: 'M 280 988 H 336', labels: [] },
  {
    id: 'consistency-judge', d: 'M 592 916 H 656',
    box: { x: 664, y: 898, w: 48, h: 12 },
    labels: [{ text: '兩項一起看', x: 668, y: 907 }],
  },
  {
    id: 'rate-judge',
    d: 'M 592 988 H 624 A 8 8 0 0 0 632 980 V 948 A 8 8 0 0 1 640 940 H 656',
    labels: [],
  },
  {
    id: 'judge-open', d: 'M 848 924 H 904',
    box: { x: 856, y: 902, w: 36, h: 12 },
    labels: [{ text: '可接受', x: 860, y: 911 }],
  },
  {
    id: 'judge-revise', d: 'M 848 980 H 904',
    box: { x: 856, y: 958, w: 36, h: 12 },
    labels: [{ text: '不理想', x: 860, y: 967 }],
  },
  {
    id: 'settled-feedback', d: 'M 172 1014 V 1068 A 8 8 0 0 0 180 1076 H 336', soft: true,
    box: { x: 192, y: 1054, w: 48, h: 12 },
    labels: [{ text: '同一批定案', x: 196, y: 1063 }],
  },
  {
    id: 'feedback-annotator', d: 'M 592 1076 H 640', soft: true, dash: '4,3',
    labels: [{ text: '標記員自己看得到 · 不用退回也能學到', x: 648, y: 1080, size: 9 }],
  },
];

// ---------------------------------------------------------------------------
// 流程圖繪製元件（單筆／整批共用）
// ---------------------------------------------------------------------------

/** marker 的 url(#id) 是文件層級解析，同頁其他圖也有 arw/arw-ac/arw-sf，故加前綴。 */
function ArrowMarkers() {
  return (
    <defs>
      <marker id="rfdri-arw" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
        <polygon points="0 0, 8 3, 0 6" fill={MUTED} />
      </marker>
      <marker id="rfdri-arw-ac" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
        <polygon points="0 0, 8 3, 0 6" fill={ACCENT} />
      </marker>
      <marker id="rfdri-arw-sf" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
        <polygon points="0 0, 8 3, 0 6" fill={SOFT} />
      </marker>
    </defs>
  );
}

function FlowEdge({ edge, active }: { edge: EdgeDef; active: boolean }) {
  const stroke = active ? ACCENT : edge.soft ? SOFT : MUTED;
  const marker = active ? 'rfdri-arw-ac' : edge.soft ? 'rfdri-arw-sf' : 'rfdri-arw';
  return (
    <g>
      <path
        d={edge.d}
        fill="none"
        stroke={stroke}
        strokeWidth={active ? 2.2 : 1.2}
        strokeDasharray={edge.dash}
        strokeOpacity={active ? 1 : 0.85}
        markerEnd={`url(#${marker})`}
      />
      {edge.box && (
        <rect x={edge.box.x} y={edge.box.y} width={edge.box.w} height={edge.box.h} rx="2" fill={PAPER} />
      )}
      {edge.labels.map((label) => (
        <text
          key={label.text}
          x={label.x}
          y={label.y}
          fontSize={label.size ?? 8}
          fontFamily={MONO}
          textAnchor={label.anchor}
          fill={active ? ACCENT : edge.soft ? SOFT : MUTED}
        >
          {label.text}
        </text>
      ))}
    </g>
  );
}

function FlowNode({
  node,
  active,
  current,
  onActivate,
}: {
  node: NodeDef;
  active: boolean;
  current: boolean;
  /** null 代表此節點目前不可點（尚未解鎖或本來就是說明性節點）。 */
  onActivate: (() => void) | null;
}) {
  const keyActivate = (event: KeyboardEvent<SVGGElement>) => {
    if (onActivate && (event.key === 'Enter' || event.key === ' ')) {
      event.preventDefault();
      onActivate();
    }
  };

  const body = (
    <>
      {current && (
        <rect
          x={node.x - 6}
          y={node.y - 6}
          width={node.w + 12}
          height={node.h + 12}
          rx={node.rx + 4}
          fill="none"
          stroke={ACCENT}
          strokeWidth="2.4"
        />
      )}
      {node.points ? (
        <polygon
          points={node.points}
          fill={node.fill}
          stroke={active ? ACCENT : node.stroke}
          strokeWidth={active ? 1.6 : 1}
          strokeOpacity={active ? 1 : 0.6}
        />
      ) : (
        <>
          <rect x={node.x} y={node.y} width={node.w} height={node.h} rx={node.rx} fill={PAPER} />
          <rect
            x={node.x}
            y={node.y}
            width={node.w}
            height={node.h}
            rx={node.rx}
            fill={node.fill}
            stroke={active ? ACCENT : node.stroke}
            strokeWidth={active ? 1.6 : 1}
            strokeDasharray={node.dash}
            strokeOpacity={active ? 1 : 0.6}
          />
        </>
      )}
      <text
        x={node.cx}
        y={node.titleY}
        fontSize="12"
        fontWeight="600"
        textAnchor="middle"
        fill={INK}
      >
        {node.title}
      </text>
      {node.subs.map((sub) => (
        <text
          key={sub.text}
          x={node.cx}
          y={sub.y}
          fontSize="9"
          fontFamily={MONO}
          textAnchor="middle"
          fill={sub.soft ? SOFT : MUTED}
        >
          {sub.text}
        </text>
      ))}
    </>
  );

  // 不可點的節點仍要帶 aria-current，否則整批流程那個「目前在這」的節點
  // 只有視覺高亮、輔助科技讀不到。
  if (!onActivate) return <g aria-current={current ? 'step' : undefined}>{body}</g>;

  return (
    <g
      role="button"
      tabIndex={0}
      aria-label={`節點：${node.title}`}
      aria-current={current ? 'step' : undefined}
      style={{ cursor: 'pointer' }}
      onClick={onActivate}
      onKeyDown={keyActivate}
    >
      {body}
    </g>
  );
}

/** 依決策／仲裁／例外處置，算出目前該點亮哪幾條線。 */
function computeActiveEdges(state: SingleFlowState): string[] {
  const edges = ['submit-review', 'review-decide'];
  if (state.decision === null) return edges;
  if (state.decision === 'approve') {
    edges.push('decide-finalized');
    return edges;
  }
  edges.push('decide-dispute', 'dispute-arbitrate');
  if (state.arbitration === null) return edges;
  if (state.arbitration !== 'reject') {
    edges.push('arbitrate-finalized');
    return edges;
  }
  edges.push('arbitrate-exception', 'exception-owner');
  if (state.exceptionAction === 'exclude_from_dataset') edges.push('owner-removed');
  else if (state.exceptionAction !== null) edges.push('owner-finalized');
  return edges;
}

function SingleFlowDiagram({
  state,
  path,
  onJump,
}: {
  state: SingleFlowState;
  path: number[];
  onJump: (step: number) => void;
}) {
  const activeEdges = computeActiveEdges(state);
  const currentIndex = path.indexOf(state.step);

  // NoteCraft 的 Tailwind 產出不含 overflow-x-auto（實測 computed 為 visible），
  // 外層 figure 又是 overflow-x:hidden，靠 class 會被硬裁掉且無法捲動；
  // 故與 MDX 內嵌原圖一致，改用 inline style。
  return (
    <div style={{ overflowX: 'auto' }}>
      <svg
        viewBox="24 12 920 704"
        role="group"
        aria-label="試標單筆審核流程圖，可點擊節點跳到該步驟"
        style={{ width: '100%', minWidth: 800, display: 'block', fontFamily: 'Inter, "Noto Sans TC", sans-serif' }}
      >
        <rect x="24" y="12" width="920" height="704" fill={PAPER} />
        <ArrowMarkers />

        <text x="40" y="32" fill={MUTED} fontSize="8" fontFamily={MONO} letterSpacing="0.18em">
          單筆流程 · 一份樣本搭一位標記員
        </text>

        {SINGLE_EDGES.map((edge) => (
          <FlowEdge key={edge.id} edge={edge} active={activeEdges.includes(edge.id)} />
        ))}

        {/* 審核員逐份審核底下的附註藥丸：不是節點，不可點 */}
        <rect x="340" y="200" width="120" height="24" rx="12" fill="rgba(30,27,75,0.05)" stroke={MUTED} strokeWidth="1" />
        <text x="400" y="216" fill={MUTED} fontSize="9" fontFamily={MONO} textAnchor="middle">
          按下送出審核才算數
        </text>

        {SINGLE_NODES.map((node) => {
          const stepIndex = node.step === null ? -1 : path.indexOf(node.step);
          const unlocked = stepIndex !== -1;
          // 只有已經走過的節點可點；stepIndex === -1（不在目前路徑上）也算沒走過，
          // 否則 -1 <= currentIndex 會讓還沒解鎖的節點誤判成可點。
          const reached = stepIndex !== -1 && currentIndex !== -1 && stepIndex <= currentIndex;
          return (
            <FlowNode
              key={node.id}
              node={node}
              active={unlocked}
              current={node.step === state.step}
              onActivate={reached ? () => onJump(node.step as number) : null}
            />
          );
        })}
      </svg>
    </div>
  );
}

function BatchFlowDiagram({
  judgment,
  onJudge,
}: {
  judgment: BatchJudgment | null;
  onJudge: (next: BatchJudgment) => void;
}) {
  const activeEdges = [
    'submitted-pending',
    'raw-consistency',
    'settled-rate',
    'consistency-judge',
    'rate-judge',
    'settled-feedback',
    'feedback-annotator',
  ];
  if (judgment === 'acceptable') activeEdges.push('judge-open');
  if (judgment === 'unacceptable') activeEdges.push('judge-revise');

  const OUTCOME_OF: Record<string, BatchJudgment> = {
    'open-official': 'acceptable',
    'revise-guideline': 'unacceptable',
  };

  return (
    <div style={{ overflowX: 'auto' }}>
      <svg
        viewBox="24 740 1152 424"
        role="group"
        aria-label="試標整批判讀流程圖，可點擊兩個出口節點決定判讀結果"
        style={{ width: '100%', minWidth: 1000, display: 'block', fontFamily: 'Inter, "Noto Sans TC", sans-serif' }}
      >
        <rect x="24" y="740" width="1152" height="424" fill={PAPER} />
        <ArrowMarkers />

        <line x1="40" y1="748" x2="1160" y2="748" stroke="rgba(30,27,75,0.10)" strokeWidth="0.8" />
        <text x="40" y="764" fill={MUTED} fontSize="8" fontFamily={MONO} letterSpacing="0.18em">
          整批流程 · 全部試標跑完之後
        </text>

        {BATCH_EDGES.map((edge) => (
          <FlowEdge key={edge.id} edge={edge} active={activeEdges.includes(edge.id)} />
        ))}

        {BATCH_NODES.map((node) => {
          const outcome = OUTCOME_OF[node.id];
          return (
            <FlowNode
              key={node.id}
              node={node}
              active={outcome === undefined || judgment === outcome}
              current={
                outcome === undefined ? node.id === 'owner-judges' && judgment === null : judgment === outcome
              }
              onActivate={outcome === undefined ? null : () => onJudge(outcome)}
            />
          );
        })}

        <text
          x="40"
          y="1144"
          fill={MUTED}
          fontSize="14"
          fontStyle="italic"
          fontFamily='"Crimson Pro", "Noto Serif TC", Georgia, serif'
        >
          審核員的每一次決定只影響一份標記；要整批跑完，才看得出指引哪裡不夠清楚。
        </text>
      </svg>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Single-unit flow
// ---------------------------------------------------------------------------

function ScaleToggle({
  mode,
  onChange,
}: {
  mode: ScaleMode;
  onChange: (mode: ScaleMode) => void;
}) {
  return (
    <div
      role="tablist"
      aria-label="檢視尺度切換"
      className="inline-flex gap-1 rounded-lg border border-slate-200 bg-white p-1"
    >
      {(
        [
          { value: 'single' as const, label: '單筆' },
          { value: 'batch' as const, label: '整批' },
        ]
      ).map((option) => (
        <button
          key={option.value}
          type="button"
          role="tab"
          aria-selected={mode === option.value}
          onClick={() => onChange(option.value)}
          className={clsx(
            'rounded-lg px-3 py-1.5 text-sm font-medium transition-colors',
            mode === option.value ? 'bg-indigo-50 text-indigo-600' : 'text-slate-500',
          )}
        >
          {option.label}
        </button>
      ))}
    </div>
  );
}

function StepDetailPanel({
  id,
  label,
  detail,
}: {
  id: number;
  label: string;
  detail: string;
}) {
  const shouldReduceMotion = useReducedMotion();
  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={id}
        initial={shouldReduceMotion ? false : { opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        exit={shouldReduceMotion ? { opacity: 1 } : { opacity: 0, y: -6 }}
        transition={{ duration: shouldReduceMotion ? 0 : 0.2, ease: 'easeOut' }}
        className="rounded-lg border border-slate-200 bg-slate-50 p-3"
      >
        <p className="mb-1 text-xs font-semibold text-slate-500">{`目前步驟：${label}`}</p>
        <p className="text-sm text-slate-600">{detail}</p>
      </motion.div>
    </AnimatePresence>
  );
}

function DecisionButtons({
  decision,
  locked,
  onSelect,
}: {
  decision: ReviewDecision | null;
  locked: boolean;
  onSelect: (next: ReviewDecision) => void;
}) {
  return (
    <div className="flex flex-wrap gap-2">
      {(['approve', 'modify', 'bypass'] as const).map((d) => (
        <button
          key={d}
          type="button"
          aria-pressed={decision === d}
          disabled={locked}
          onClick={() => onSelect(d)}
          className={clsx(
            'rounded-lg border px-3 py-1.5 text-sm font-medium transition-colors',
            decision === d
              ? d === 'approve'
                ? 'border-emerald-500 bg-emerald-50 text-emerald-700'
                : 'border-indigo-500 bg-indigo-50 text-indigo-600'
              : 'border-slate-200 text-slate-600',
          )}
        >
          {DECISION_LABEL[d]}
        </button>
      ))}
      <button
        type="button"
        aria-disabled="true"
        onClick={(e) => e.preventDefault()}
        className="inline-flex cursor-not-allowed items-center gap-1 rounded-lg border border-slate-100 bg-slate-50 px-3 py-1.5 text-sm text-slate-400"
      >
        <Ban size={14} />
        退回重標（不存在）
      </button>
    </div>
  );
}

function ArbitrationButtons({
  arbitration,
  locked,
  onSelect,
}: {
  arbitration: ArbitrationOutcome | null;
  locked: boolean;
  onSelect: (next: ArbitrationOutcome) => void;
}) {
  return (
    <div className="flex flex-wrap gap-2">
      {(['adopt_a', 'adopt_b', 'reject'] as const).map((a) => (
        <button
          key={a}
          type="button"
          aria-pressed={arbitration === a}
          disabled={locked}
          onClick={() => onSelect(a)}
          className={clsx(
            'rounded-lg border px-3 py-1.5 text-sm font-medium transition-colors',
            arbitration === a
              ? 'border-indigo-500 bg-indigo-50 text-indigo-600'
              : 'border-slate-200 text-slate-600',
          )}
        >
          {ARBITRATION_LABEL[a]}
        </button>
      ))}
      <button
        type="button"
        aria-disabled="true"
        onClick={(e) => e.preventDefault()}
        className="inline-flex cursor-not-allowed items-center gap-1 rounded-lg border border-slate-100 bg-slate-50 px-3 py-1.5 text-sm text-slate-400"
      >
        <Ban size={14} />
        仲裁者自訂第三種答案（不存在）
      </button>
    </div>
  );
}

function ExceptionPoolPanel({
  state,
  locked,
  onSelectAction,
  onReasonChange,
  onConfirm,
}: {
  state: SingleFlowState;
  locked: boolean;
  onSelectAction: (next: ExceptionAction) => void;
  onReasonChange: (value: string) => void;
  onConfirm: () => void;
}) {
  const reasonFilled = state.exceptionReason.trim().length > 0;
  return (
    <div className="space-y-3">
      <div className="flex flex-wrap gap-2">
        {(['adopt_annotator', 'adopt_reviewer', 'exclude_from_dataset'] as const).map((a) => (
          <button
            key={a}
            type="button"
            aria-pressed={state.exceptionAction === a}
            disabled={locked}
            onClick={() => onSelectAction(a)}
            className={clsx(
              'rounded-lg border px-3 py-1.5 text-sm font-medium transition-colors',
              state.exceptionAction === a
                ? 'border-indigo-500 bg-indigo-50 text-indigo-600'
                : 'border-slate-200 text-slate-600',
            )}
          >
            {EXCEPTION_LABEL[a]}
          </button>
        ))}
      </div>
      <div>
        <label htmlFor="review-flow-exception-reason" className="mb-1 block text-xs font-medium text-slate-500">
          處置理由（必填）
        </label>
        <textarea
          id="review-flow-exception-reason"
          value={state.exceptionReason}
          onChange={(e) => onReasonChange(e.target.value)}
          disabled={locked}
          rows={2}
          placeholder="請說明處置理由"
          className="w-full rounded-lg border border-slate-200 px-2.5 py-1.5 text-sm text-slate-700"
        />
        {!reasonFilled && <p className="mt-1 text-xs text-slate-500">請填寫理由</p>}
      </div>
      <button
        type="button"
        onClick={onConfirm}
        disabled={locked || !state.exceptionAction || !reasonFilled}
        className="rounded-lg bg-indigo-600 px-3.5 py-1.5 text-sm font-medium text-white transition-colors"
      >
        確認收尾
      </button>
    </div>
  );
}

function LockedNotice({ onReset }: { onReset: () => void }) {
  return (
    <div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-1.5">
      <p className="text-xs text-slate-600">已定稿：這一步的決定已鎖定，不能再修改。</p>
      <button type="button" onClick={onReset} className="text-xs font-medium text-indigo-600 transition-colors">
        重新示範一次
      </button>
    </div>
  );
}

function FinalizedTrace({ state, onReset }: { state: SingleFlowState; onReset: () => void }) {
  return (
    <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3">
      <p className="mb-1 text-xs font-semibold text-emerald-700">已定稿</p>
      <p className="text-sm text-emerald-800">{buildTraceString(state)}</p>
      <button
        type="button"
        onClick={onReset}
        className="mt-3 text-xs font-medium text-indigo-600 transition-colors"
      >
        重新示範一次
      </button>
    </div>
  );
}

function StepNav({
  canGoPrev,
  canGoNext,
  onPrev,
  onNext,
}: {
  canGoPrev: boolean;
  canGoNext: boolean;
  onPrev: () => void;
  onNext: () => void;
}) {
  return (
    <div
      className="flex items-center justify-between border-t border-slate-100 pt-3"
      onKeyDown={(e) => {
        if (e.key === 'ArrowRight' && canGoNext) onNext();
        if (e.key === 'ArrowLeft' && canGoPrev) onPrev();
      }}
    >
      <button
        type="button"
        onClick={onPrev}
        disabled={!canGoPrev}
        className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600 transition-colors"
      >
        上一步
      </button>
      <button
        type="button"
        onClick={onNext}
        disabled={!canGoNext}
        className="rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-medium text-white transition-colors"
      >
        下一步
      </button>
    </div>
  );
}

function SingleUnitFlow() {
  const [state, setState] = useState<SingleFlowState>(INITIAL_SINGLE_STATE);
  const path = computeVisiblePath(state.decision, state.arbitration, state.exceptionConfirmed);
  const currentDef = STEP_DEFS[state.step];
  const canGoPrev = path.indexOf(state.step) > 0;
  const canGoNext = computeCanGoNext(state, path);

  function moveTo(s: SingleFlowState, step: number): SingleFlowState {
    return { ...s, step, finalized: s.finalized || step === 7 };
  }

  function jumpTo(id: number) {
    setState((s) => moveTo(s, id));
  }

  function goPrev() {
    const idx = path.indexOf(state.step);
    if (idx > 0) setState((s) => moveTo(s, path[idx - 1]));
  }

  function goNext() {
    const idx = path.indexOf(state.step);
    if (idx !== -1 && idx < path.length - 1) setState((s) => moveTo(s, path[idx + 1]));
  }

  function selectDecision(next: ReviewDecision) {
    setState((s) => s.finalized ? s : ({
      ...s,
      decision: next,
      arbitration: null,
      exceptionAction: null,
      exceptionReason: '',
      exceptionConfirmed: false,
    }));
  }

  function selectArbitration(next: ArbitrationOutcome) {
    setState((s) => s.finalized ? s : ({
      ...s,
      arbitration: next,
      exceptionAction: null,
      exceptionReason: '',
      exceptionConfirmed: false,
    }));
  }

  function selectExceptionAction(next: ExceptionAction) {
    setState((s) => (s.finalized ? s : { ...s, exceptionAction: next }));
  }

  function setExceptionReason(value: string) {
    setState((s) => (s.finalized ? s : { ...s, exceptionReason: value }));
  }

  function confirmException() {
    setState((s) => {
      if (!s.exceptionAction || s.exceptionReason.trim().length === 0) return s;
      return moveTo({ ...s, exceptionConfirmed: true }, 7);
    });
  }

  function reset() {
    setState(INITIAL_SINGLE_STATE);
  }

  return (
    <div className="space-y-4">
      <SingleFlowDiagram state={state} path={path} onJump={jumpTo} />
      <StepDetailPanel id={state.step} label={currentDef.label} detail={currentDef.detail} />
      {state.finalized && [3, 5, 6].includes(state.step) && <LockedNotice onReset={reset} />}
      {state.step === 3 && <DecisionButtons decision={state.decision} locked={state.finalized} onSelect={selectDecision} />}
      {state.step === 5 && (
        <ArbitrationButtons arbitration={state.arbitration} locked={state.finalized} onSelect={selectArbitration} />
      )}
      {state.step === 6 && (
        <ExceptionPoolPanel
          state={state}
          locked={state.finalized}
          onSelectAction={selectExceptionAction}
          onReasonChange={setExceptionReason}
          onConfirm={confirmException}
        />
      )}
      {state.step === 7 && <FinalizedTrace state={state} onReset={reset} />}
      <StepNav canGoPrev={canGoPrev} canGoNext={canGoNext} onPrev={goPrev} onNext={goNext} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Batch summary
// ---------------------------------------------------------------------------

interface ModifiedRateDatum {
  readonly name: string;
  readonly rate: number;
}

const MODIFIED_RATE_DATA: ModifiedRateDatum[] = [
  { name: '標記員 A', rate: 18 },
  { name: '標記員 B', rate: 32 },
  { name: '標記員 C', rate: 24 },
];

const CONSISTENCY_RATE = 82;

function ConsistencyStat() {
  return (
    <div className="rounded-lg border border-slate-200 bg-white p-4">
      <p className="text-4xl font-bold text-indigo-600">{CONSISTENCY_RATE}%</p>
      <p className="mt-1 text-xs text-slate-500">標記一致性（示意數值）</p>
    </div>
  );
}

function ModifiedRateChart() {
  return (
    <div className="rounded-lg border border-slate-200 bg-white p-4">
      <p className="mb-2 text-xs text-slate-500">標記員被修改的比例（示意數值）</p>
      <div style={{ width: '100%', height: 180 }}>
        <ResponsiveContainer>
          <BarChart data={MODIFIED_RATE_DATA} margin={{ top: 4, right: 8, left: 0, bottom: 0 }}>
            <CartesianGrid vertical={false} stroke="#E2E8F0" />
            <XAxis dataKey="name" tick={{ fontSize: 11, fill: '#64748B' }} axisLine={{ stroke: '#E2E8F0' }} tickLine={false} />
            <YAxis tick={{ fontSize: 11, fill: '#64748B' }} axisLine={{ stroke: '#E2E8F0' }} tickLine={false} unit="%" width={36} />
            <Tooltip cursor={{ fill: '#EEF2FF' }} formatter={(value: number) => [`${value}%`, '修正率']} />
            <Bar dataKey="rate" fill="#6366F1" radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

function JudgmentPanel({ judgment }: { judgment: BatchJudgment | null }) {
  let content: ReactNode;
  if (judgment === null) {
    content = (
      <p className="text-xs text-slate-400">
        點流程圖右側的「開放正式標記」或「修改指引後再跑一輪試標」，選擇主持人的判讀結果。
      </p>
    );
  } else if (judgment === 'acceptable') {
    content = (
      <p className="flex items-center gap-1.5 text-sm font-medium text-emerald-700">
        開放正式標記
        <ArrowRight size={16} />
      </p>
    );
  } else {
    content = (
      <div className="space-y-1">
        <p className="text-sm text-slate-700">修改指引 → 再跑一輪試標</p>
        <p className="text-xs text-slate-500">（改的是指引，不是退回個別樣本）</p>
      </div>
    );
  }
  return <div className="rounded-lg border border-slate-200 bg-white p-4">{content}</div>;
}

function FeedbackAside() {
  return (
    <div className="flex gap-2.5 rounded-lg border border-slate-200 bg-white p-3">
      <Eye size={16} className="mt-0.5 shrink-0 text-slate-400" />
      <div>
        <p className="text-xs font-semibold text-slate-600">試標歷程回饋</p>
        <p className="mt-1 text-xs text-slate-500">
          標記員自己看得到哪幾項被改、被誰定案，不用退回也能學到。
        </p>
      </div>
    </div>
  );
}

function BatchSummary() {
  const [judgment, setJudgment] = useState<BatchJudgment | null>(null);
  return (
    <div className="space-y-4">
      <BatchFlowDiagram judgment={judgment} onJudge={setJudgment} />
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <ConsistencyStat />
        <ModifiedRateChart />
      </div>
      <JudgmentPanel judgment={judgment} />
      <FeedbackAside />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Root component
// ---------------------------------------------------------------------------

export default function ReviewFlowDryRunInteractive() {
  const [mode, setMode] = useState<ScaleMode>('single');
  return (
    <div className="rfdr-root not-prose w-full space-y-5">
      <style dangerouslySetInnerHTML={{ __html: SCOPED_CSS }} />
      <ScaleToggle mode={mode} onChange={setMode} />
      {mode === 'single' ? <SingleUnitFlow /> : <BatchSummary />}
    </div>
  );
}
