// 本檔為 generated view——請勿手動編輯
// Generated by NoteCraft @ai-visualize (content-visualize skill); regenerate from the marker in specs/annotation/015-annotation-workspace/diagrams.mdx.

import { useMemo, useState, type Dispatch, type KeyboardEvent, type ReactNode, type SetStateAction } from 'react';
import {
  Clock,
  TriangleAlert,
  Lock,
  Ban,
  Check,
  Pencil,
  CircleHelp,
  Scale,
  ArrowRight,
  type LucideIcon,
} from 'lucide-react';
import clsx from 'clsx';

// ---------------------------------------------------------------------------
// SCOPED_CSS —— NoteCraft 的 tailwind content glob 是相對於它自己的安裝目錄
// （~/.notecraft/app-0.5.1/tailwind.config.mjs: "./src/**/*"），生成元件落在
// <repo>/.notecraft/components/ 不在掃描範圍內，JIT 從未看過這些 class，
// 實測 84 個 class 有 74 個對不到任何規則（p-4 → padding:0、text-xs → 18px）。
// 故本元件自帶所用到的 utility，全部限定在 .rusm-root 底下，不依賴宿主 CSS。
// ---------------------------------------------------------------------------

const SCOPED_CSS = `
.rusm-root { font-size: 0.875rem; line-height: 1.5; color: #334155; }
.rusm-root p, .rusm-root ul, .rusm-root ol, .rusm-root li { margin: 0; }
.rusm-root button { font: inherit; color: inherit; background: none; border: 0; }

.rusm-root .flex { display: flex; }
.rusm-root .grid { display: grid; }
.rusm-root .block { display: block; }
.rusm-root .inline { display: inline; }
.rusm-root .grid-cols-1 { grid-template-columns: repeat(1, minmax(0, 1fr)); }
.rusm-root .items-center { align-items: center; }
.rusm-root .justify-between { justify-content: space-between; }
.rusm-root .flex-wrap { flex-wrap: wrap; }
.rusm-root .shrink-0 { flex-shrink: 0; }
.rusm-root .w-full { width: 100%; }
.rusm-root .text-left { text-align: left; }
.rusm-root .min-h-\\[72px\\] { min-height: 72px; }
.rusm-root .min-h-\\[92px\\] { min-height: 92px; }

.rusm-root .gap-1 { gap: 0.25rem; }
.rusm-root .gap-2 { gap: 0.5rem; }
.rusm-root .gap-6 { gap: 1.5rem; }
.rusm-root .p-3 { padding: 0.75rem; }
.rusm-root .p-4 { padding: 1rem; }
.rusm-root .px-2 { padding-left: 0.5rem; padding-right: 0.5rem; }
.rusm-root .px-3 { padding-left: 0.75rem; padding-right: 0.75rem; }
.rusm-root .py-1 { padding-top: 0.25rem; padding-bottom: 0.25rem; }
.rusm-root .py-1\\.5 { padding-top: 0.375rem; padding-bottom: 0.375rem; }
.rusm-root .py-2 { padding-top: 0.5rem; padding-bottom: 0.5rem; }
.rusm-root .mb-1 { margin-bottom: 0.25rem; }
.rusm-root .ml-1 { margin-left: 0.25rem; }
.rusm-root .mt-2 { margin-top: 0.5rem; }
.rusm-root .space-y-1 > * + * { margin-top: 0.25rem; }
.rusm-root .space-y-2 > * + * { margin-top: 0.5rem; }
.rusm-root .space-y-3 > * + * { margin-top: 0.75rem; }
.rusm-root .space-y-4 > * + * { margin-top: 1rem; }
.rusm-root .space-y-6 > * + * { margin-top: 1.5rem; }

.rusm-root .border { border-width: 1px; border-style: solid; border-color: #E2E8F0; }
.rusm-root .rounded-lg { border-radius: 0.5rem; }
.rusm-root .border-slate-200 { border-color: #E2E8F0; }
.rusm-root .border-indigo-500 { border-color: #6366F1; }
.rusm-root .border-emerald-500 { border-color: #10B981; }
.rusm-root .border-red-200 { border-color: #FECACA; }
.rusm-root .border-red-700 { border-color: #B91C1C; }
.rusm-root .border-yellow-200 { border-color: #FDE68A; }

.rusm-root .bg-white { background-color: #FFFFFF; }
.rusm-root .bg-indigo-50 { background-color: #EEF2FF; }
.rusm-root .bg-green-50 { background-color: #F0FDF4; }
.rusm-root .bg-red-50 { background-color: #FEF2F2; }
.rusm-root .bg-yellow-50 { background-color: #FEFCE8; }

.rusm-root .text-xs { font-size: 0.75rem; line-height: 1rem; }
.rusm-root .text-sm { font-size: 0.875rem; line-height: 1.25rem; }
.rusm-root .font-medium { font-weight: 500; }
.rusm-root .text-slate-400 { color: #94A3B8; }
.rusm-root .text-slate-500 { color: #64748B; }
.rusm-root .text-slate-600 { color: #475569; }
.rusm-root .text-slate-700 { color: #334155; }
.rusm-root .text-slate-800 { color: #1E293B; }
.rusm-root .text-indigo-600 { color: #4F46E5; }
.rusm-root .text-emerald-600 { color: #059669; }
.rusm-root .text-red-700 { color: #B91C1C; }
.rusm-root .text-yellow-700 { color: #A16207; }

.rusm-root .opacity-50 { opacity: 0.5; }
.rusm-root .pointer-events-none { pointer-events: none; }
.rusm-root .transition-colors { transition: color 150ms, background-color 150ms, border-color 150ms; }
.rusm-root button:disabled { opacity: 0.5; cursor: not-allowed; }
.rusm-root [role="button"] { cursor: pointer; }

@media (min-width: 640px) {
  .rusm-root .sm\\:grid-cols-\\[1fr_320px\\] { grid-template-columns: 1fr 320px; }
}
@media (prefers-reduced-motion: reduce) {
  .rusm-root .transition-colors { transition: none; }
}
`;

// ---------------------------------------------------------------------------
// 型別 —— 對齊 REVIEW_UNIT_STATUS（FR-051）與 REVIEW_DECISIONS（FR-092）
// ---------------------------------------------------------------------------

type ReviewUnitStatus = 'pending' | 'disputed' | 'finalized';
type ReviewDecision = 'approve' | 'modify' | 'bypass';

interface SimState {
  annotatorSubmitted: boolean;
  reviewerSubmitted: boolean;
  outKeyDecisions: { outKeyA: ReviewDecision; outKeyB: ReviewDecision };
  disputedResolved: { outKeyA: boolean; outKeyB: boolean };
}

// ---------------------------------------------------------------------------
// 模組層常數 —— 逐字對齊 FR-051 判定式與規劃書，不得意譯或補上規劃書沒有的轉換
// ---------------------------------------------------------------------------

const TRANSITIONS = [
  {
    id: 'null-pending',
    from: null,
    to: 'pending',
    guard: '標記員提交，系統指派 1 位審核員（FR-093）',
    clause: 'FR-051 判定式第 2 句之前提',
  },
  {
    id: 'pending-finalized',
    from: 'pending',
    to: 'finalized',
    guard: '審核員逐項決策皆為「通過」',
    clause: 'FR-051 判定式第 3 句',
  },
  {
    id: 'pending-disputed',
    from: 'pending',
    to: 'disputed',
    guard: '任一項決策為「修正」或「無法判定」',
    clause: 'FR-051 判定式第 4 句',
  },
  {
    id: 'disputed-finalized',
    from: 'disputed',
    to: 'finalized',
    guard: '所有爭議項皆已解決（仲裁定案 FR-061 或最終例外池收尾 FR-095）',
    clause: 'FR-051 判定式第 5 句',
  },
  {
    id: 'disputed-disputed',
    from: 'disputed',
    to: 'disputed',
    guard: '仍有未解決的爭議項，維持爭議中',
    clause: 'FR-051 判定式第 5 句（否定分支，自留迴圈）',
  },
] as const;

const NONEXISTENT = [
  {
    id: 'interim-states',
    label: '「已同意」／「已修改」中繼態',
    reason:
      'v5.0.0（issue #596）隨 REVIEW_UNIT_STATUS 收斂為三態而移除：其存在前提是「已表態人數未達 min_reviewers 門檻」，單人接力下一個審核單位恰指派一位審核員（FR-093），該區間不存在，兩態必恆為瞬時值。',
  },
  {
    id: 'disputed-to-pending',
    label: '爭議中 → 待審（退回）',
    reason: '不存在：爭議中不回退，未解決項只使 disputed 自留（FR-051）。',
  },
  {
    id: 'finalized-to-any',
    label: '已定稿 → 任何狀態',
    reason: '不存在：finalized 為終態，出邊為空集合（FR-051）。',
  },
  {
    id: 'pending-to-null',
    label: '待審 → 不成立',
    reason: '不存在：標記員提交後不會退回不成立（FR-051）。',
  },
  {
    id: 'reject-decision',
    label: '「退回重標」決策值',
    reason: '不在 REVIEW_DECISIONS 內，兩種 run_type 皆不得出現；退回控件、退回決策值、退回歷程產生點一律不存在（FR-092）。',
  },
  {
    id: 'auto-convergence',
    label: '自動收斂（多數決）',
    reason: 'DISPUTE_CONVERGENCE_RULE 已於 v5.0.0 廢止，爭議項必須全數由仲裁者逐項裁定（FR-061）。',
  },
  {
    id: 'run-type-branch',
    label: '依 run_type 分流的狀態機',
    reason: '不存在：定址與判定於兩種 run_type 完全一致（FR-051）。',
  },
  {
    id: 'draft-affects-state',
    label: '未送出草稿改變狀態',
    reason: '不存在：草稿不計入狀態解析（FR-051）。',
  },
] as const;

type TransitionId = (typeof TRANSITIONS)[number]['id'];
type NonexistentId = (typeof NONEXISTENT)[number]['id'];

// 圖上的節點比 REVIEW_UNIT_STATUS 多一個「不成立」（推導為 null），它不是狀態集合的
// 成員，只是判定式第 1 句的出口，故另立 NodeId 而不擴充 ReviewUnitStatus。
type NodeId = 'null' | ReviewUnitStatus;

type Selection = { kind: 'transition'; id: TransitionId } | { kind: 'state'; id: NodeId } | null;

const STATE_LABELS: Record<NodeId, string> = {
  null: '不成立審核單位',
  pending: '待審',
  disputed: '爭議中',
  finalized: '已定稿',
};

const STATUS_VISUALS: Record<
  ReviewUnitStatus,
  { label: string; text: string; bg: string; border: string; icon: LucideIcon }
> = {
  pending: { label: '待審', text: 'text-slate-500', bg: 'bg-white', border: 'border-slate-200', icon: Clock },
  disputed: {
    label: '爭議中',
    text: 'text-yellow-700',
    bg: 'bg-yellow-50',
    border: 'border-yellow-200',
    icon: TriangleAlert,
  },
  finalized: {
    label: '已定稿',
    text: 'text-emerald-600',
    bg: 'bg-green-50',
    border: 'border-emerald-500',
    icon: Lock,
  },
};

const DECISION_VISUALS: Record<ReviewDecision, { label: string; icon: LucideIcon }> = {
  approve: { label: '通過', icon: Check },
  modify: { label: '修正', icon: Pencil },
  bypass: { label: '無法判定', icon: CircleHelp },
};

// ---------------------------------------------------------------------------
// deriveReviewUnitStatus —— 逐句實作 FR-051 五句判定式，不用捷徑邏輯
// ---------------------------------------------------------------------------

function deriveReviewUnitStatus(sim: SimState): ReviewUnitStatus | null {
  // FR-051 判定式第 1 句：標記員未提交 → 不成立審核單位（推導為 null）
  if (!sim.annotatorSubmitted) {
    return null;
  }

  // FR-051 判定式第 2 句：該單位之指派審核員（FR-093）尚未提交 → pending
  if (!sim.reviewerSubmitted) {
    return 'pending';
  }

  const decisionA = sim.outKeyDecisions.outKeyA;
  const decisionB = sim.outKeyDecisions.outKeyB;

  // FR-051 判定式第 3 句：審核員逐項決策皆為 approve → finalized
  const allApproved = decisionA === 'approve' && decisionB === 'approve';
  if (allApproved) {
    return 'finalized';
  }

  // FR-051 判定式第 4 句：任一項決策為 modify 或 bypass → disputed
  const outKeyADisputed = decisionA === 'modify' || decisionA === 'bypass';
  const outKeyBDisputed = decisionB === 'modify' || decisionB === 'bypass';
  const anyDisputed = outKeyADisputed || outKeyBDisputed;

  if (anyDisputed) {
    // FR-051 判定式第 5 句：disputed 單位之所有爭議項皆已解決
    // （仲裁定案 FR-061 或最終例外池收尾 FR-095）→ finalized，否則維持 disputed
    const outKeyAResolved = !outKeyADisputed || sim.disputedResolved.outKeyA;
    const outKeyBResolved = !outKeyBDisputed || sim.disputedResolved.outKeyB;
    const allResolved = outKeyAResolved && outKeyBResolved;
    return allResolved ? 'finalized' : 'disputed';
  }

  // decisions 值域僅 { approve, modify, bypass }：allApproved 為否時 anyDisputed 恆真，
  // 此分支理論上不可達，僅為滿足函式回傳型別的窮舉檢查而保留。
  return 'disputed';
}

// deriveClauseLabel 僅供 UI 顯示「依 FR-051 判定式第 N 句」用，鏡射上方判定式的
// 同一組守衛條件，不影響 deriveReviewUnitStatus 本身的判定結果。
function deriveClauseLabel(sim: SimState): string {
  if (!sim.annotatorSubmitted) {
    return 'FR-051 判定式第 1 句';
  }
  if (!sim.reviewerSubmitted) {
    return 'FR-051 判定式第 2 句';
  }

  const decisionA = sim.outKeyDecisions.outKeyA;
  const decisionB = sim.outKeyDecisions.outKeyB;
  const allApproved = decisionA === 'approve' && decisionB === 'approve';
  if (allApproved) {
    return 'FR-051 判定式第 3 句';
  }

  const outKeyADisputed = decisionA === 'modify' || decisionA === 'bypass';
  const outKeyBDisputed = decisionB === 'modify' || decisionB === 'bypass';
  const outKeyAResolved = !outKeyADisputed || sim.disputedResolved.outKeyA;
  const outKeyBResolved = !outKeyBDisputed || sim.disputedResolved.outKeyB;
  const allResolved = outKeyAResolved && outKeyBResolved;

  return allResolved ? 'FR-051 判定式第 5 句' : 'FR-051 判定式第 4 句（成立爭議）／第 5 句否定分支（維持爭議中）';
}

// ---------------------------------------------------------------------------
// 子元件
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 圖形幾何 —— 座標逐點沿用靜態原圖 diagrams/review-unit-state-machine.html，
// 讓互動版與原圖可並列比對。此處只在既有圖形上加互動，不重新佈局。
// ---------------------------------------------------------------------------

const PAPER = '#F5F3FF';
const INK = '#1E1B4B';
const MUTED = '#64748B';
const SOFT = '#94A3B8';
const ACCENT = '#6366F1';

const NODE_GEOMETRY: {
  id: NodeId;
  x: number;
  title: string;
  subtitle: string;
  fill: string;
  stroke: string;
  dash?: string;
}[] = [
  {
    id: 'null',
    x: 40,
    title: '不成立審核單位',
    subtitle: '推導為 null',
    fill: 'rgba(30,27,75,0.02)',
    stroke: 'rgba(30,27,75,0.20)',
    dash: '4,3',
  },
  { id: 'pending', x: 360, title: '待審', subtitle: 'pending', fill: '#FFFFFF', stroke: INK },
  { id: 'disputed', x: 680, title: '爭議中', subtitle: 'disputed', fill: '#EEF2FF', stroke: ACCENT },
  { id: 'finalized', x: 1000, title: '已定稿', subtitle: 'finalized', fill: 'rgba(30,27,75,0.05)', stroke: MUTED },
];

const EDGE_GEOMETRY: {
  id: TransitionId;
  d: string;
  labels: string[];
  box: { x: number; y: number; w: number; h: number };
  cx: number;
  ys: number[];
  accent?: boolean;
}[] = [
  {
    id: 'null-pending',
    d: 'M 200 232 H 360',
    labels: ['標記員提交', '系統指派 1 位審核員'],
    box: { x: 216, y: 196, w: 128, h: 28 },
    cx: 280,
    ys: [208, 220],
  },
  {
    id: 'pending-finalized',
    d: 'M 440 200 V 144 A 8 8 0 0 1 448 136 H 1072 A 8 8 0 0 1 1080 144 V 200',
    labels: ['審核員逐項決策', '皆為 approve'],
    box: { x: 680, y: 100, w: 176, h: 28 },
    cx: 768,
    ys: [112, 124],
  },
  {
    id: 'pending-disputed',
    d: 'M 520 232 H 680',
    labels: ['任一項決策為', 'modify 或 bypass'],
    box: { x: 536, y: 196, w: 128, h: 28 },
    cx: 600,
    ys: [208, 220],
  },
  {
    id: 'disputed-finalized',
    d: 'M 840 232 H 1000',
    labels: ['所有爭議項皆已解決', '仲裁定案（FR-061）', '或例外池收尾（FR-095）'],
    box: { x: 856, y: 184, w: 136, h: 40 },
    cx: 924,
    ys: [196, 208, 220],
  },
  {
    id: 'disputed-disputed',
    d: 'M 720 264 V 296 A 8 8 0 0 0 728 304 H 792 A 8 8 0 0 0 800 296 V 264',
    labels: ['仍有未解決的爭議項', '維持 disputed，不回退'],
    box: { x: 656, y: 312, w: 208, h: 28 },
    cx: 760,
    ys: [324, 336],
    accent: true,
  },
];

// derivePathEdges —— 把 deriveReviewUnitStatus 走過的那條路徑還原成邊的序列，
// 好讓圖上實際亮起「這組決策走的是哪幾條線」。守衛條件與判定式本身不在這裡重算。
function derivePathEdges(sim: SimState): TransitionId[] {
  if (!sim.annotatorSubmitted) {
    return [];
  }
  if (!sim.reviewerSubmitted) {
    return ['null-pending'];
  }

  const decisionA = sim.outKeyDecisions.outKeyA;
  const decisionB = sim.outKeyDecisions.outKeyB;
  if (decisionA === 'approve' && decisionB === 'approve') {
    return ['null-pending', 'pending-finalized'];
  }

  const outKeyADisputed = decisionA === 'modify' || decisionA === 'bypass';
  const outKeyBDisputed = decisionB === 'modify' || decisionB === 'bypass';
  const outKeyAResolved = !outKeyADisputed || sim.disputedResolved.outKeyA;
  const outKeyBResolved = !outKeyBDisputed || sim.disputedResolved.outKeyB;

  return outKeyAResolved && outKeyBResolved
    ? ['null-pending', 'pending-disputed', 'disputed-finalized']
    : ['null-pending', 'pending-disputed', 'disputed-disputed'];
}

// 節點是否落在本次推導走過的路徑上（用於加一圈強調外框，不覆蓋原圖既有配色）。
function nodeOnPath(nodeId: NodeId, edges: TransitionId[]): boolean {
  if (nodeId === 'null') {
    return true;
  }
  return edges.some((id) => id.startsWith(`${nodeId}-`) || id.endsWith(`-${nodeId}`));
}

function StateDiagram({
  derivedStatus,
  pathEdges,
  selection,
  onSelect,
}: {
  derivedStatus: ReviewUnitStatus | null;
  pathEdges: TransitionId[];
  selection: Selection;
  onSelect: (selection: Selection) => void;
}) {
  const activate = (next: Selection) => onSelect(next);
  const keyActivate = (event: KeyboardEvent<SVGGElement>, next: Selection) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      onSelect(next);
    }
  };

  // NoteCraft 的 Tailwind 產出不含 overflow-x-auto（實測 computed 為 visible），
  // 外層 figure 又是 overflow-x:hidden，靠 class 會被硬裁掉且無法捲動；
  // 故與 MDX 內嵌原圖一致，改用 inline style。
  return (
    <div style={{ overflowX: 'auto' }}>
      <svg
        viewBox="0 0 1200 396"
        role="group"
        aria-label="ReviewUnit 三態狀態機流程圖，可點擊節點或轉換查看守衛條件"
        style={{ width: '100%', minWidth: 1040, display: 'block', fontFamily: 'Inter, "Noto Sans TC", sans-serif' }}
      >
        <rect width="100%" height="100%" fill={PAPER} />
        <defs>
          <marker id="rusmi-arw" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
            <polygon points="0 0, 8 3, 0 6" fill={MUTED} />
          </marker>
          <marker id="rusmi-arw-ac" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
            <polygon points="0 0, 8 3, 0 6" fill={ACCENT} />
          </marker>
          <marker id="rusmi-arw-sf" markerWidth="8" markerHeight="6" refX="7" refY="3" orient="auto">
            <polygon points="0 0, 8 3, 0 6" fill={SOFT} />
          </marker>
        </defs>

        <text x="40" y="32" fontSize="11" fill={MUTED}>
          狀態轉換 · 三態線性推進，爭議中為唯一有自留迴圈的狀態
        </text>

        {/* 起點與終點的短柄：非轉換，不可點 */}
        <circle cx="120" cy="152" r="6" fill={INK} />
        <path d="M 120 160 V 200" stroke={MUTED} strokeWidth="1.2" fill="none" markerEnd="url(#rusmi-arw)" />
        <path d="M 1080 264 V 292" stroke={MUTED} strokeWidth="1.2" fill="none" />
        <circle cx="1080" cy="304" r="8" fill="none" stroke={INK} />
        <circle cx="1080" cy="304" r="5" fill={INK} />
        <text x="1096" y="308" fontSize="10" fill={MUTED}>
          終態
        </text>

        {EDGE_GEOMETRY.map((edge) => {
          const isOnPath = pathEdges.includes(edge.id);
          const isSelected = selection?.kind === 'transition' && selection.id === edge.id;
          const transition = TRANSITIONS.find((t) => t.id === edge.id) as (typeof TRANSITIONS)[number];
          const stroke = isOnPath ? ACCENT : edge.accent ? ACCENT : isSelected ? INK : SOFT;
          const marker = isOnPath || edge.accent ? 'rusmi-arw-ac' : isSelected ? 'rusmi-arw' : 'rusmi-arw-sf';
          const next: Selection = { kind: 'transition', id: edge.id };

          return (
            <g
              key={edge.id}
              role="button"
              tabIndex={0}
              aria-label={`轉換：${transition.guard}`}
              aria-pressed={isSelected}
              style={{ cursor: 'pointer' }}
              onClick={() => activate(next)}
              onKeyDown={(event) => keyActivate(event, next)}
            >
              {isSelected && <path d={edge.d} stroke={ACCENT} strokeWidth="12" strokeOpacity="0.18" fill="none" />}
              <path d={edge.d} stroke="transparent" strokeWidth="18" fill="none" />
              <path
                d={edge.d}
                stroke={stroke}
                strokeWidth={isOnPath || isSelected ? 2.2 : 1.2}
                fill="none"
                markerEnd={`url(#${marker})`}
              />
              <rect x={edge.box.x} y={edge.box.y} width={edge.box.w} height={edge.box.h} rx="2" fill={PAPER} />
              {edge.labels.map((line, index) => (
                <text
                  key={line}
                  x={edge.cx}
                  y={edge.ys[index]}
                  fontSize="9"
                  textAnchor="middle"
                  fill={index === 0 && edge.accent ? ACCENT : MUTED}
                  fontFamily='"JetBrains Mono", ui-monospace, monospace'
                >
                  {line}
                </text>
              ))}
            </g>
          );
        })}

        {NODE_GEOMETRY.map((node) => {
          const isCurrent = node.id === 'null' ? derivedStatus === null : derivedStatus === node.id;
          const isOnPath = nodeOnPath(node.id, pathEdges);
          const isSelected = selection?.kind === 'state' && selection.id === node.id;
          const next: Selection = { kind: 'state', id: node.id };

          return (
            <g
              key={node.id}
              role="button"
              tabIndex={0}
              aria-label={`狀態：${STATE_LABELS[node.id]}`}
              aria-current={isCurrent ? 'true' : undefined}
              aria-pressed={isSelected}
              style={{ cursor: 'pointer' }}
              onClick={() => activate(next)}
              onKeyDown={(event) => keyActivate(event, next)}
            >
              {(isCurrent || isSelected) && (
                <rect
                  x={node.x - 6}
                  y={194}
                  width={172}
                  height={76}
                  rx={10}
                  fill="none"
                  stroke={ACCENT}
                  strokeWidth={isCurrent ? 2.4 : 1.4}
                  strokeDasharray={isCurrent ? undefined : '5,4'}
                />
              )}
              <rect x={node.x} y={200} width={160} height={64} rx={6} fill={PAPER} />
              <rect
                x={node.x}
                y={200}
                width={160}
                height={64}
                rx={6}
                fill={node.fill}
                stroke={node.stroke}
                strokeDasharray={node.dash}
                strokeOpacity={isOnPath ? 1 : 0.5}
              />
              <text x={node.x + 16} y={228} fontSize="12" fontWeight="600" fill={INK}>
                {node.title}
              </text>
              <text
                x={node.x + 16}
                y={246}
                fontSize="9"
                fill={MUTED}
                fontFamily='"JetBrains Mono", ui-monospace, monospace'
              >
                {node.subtitle}
              </text>
            </g>
          );
        })}

        {/* 圖例 */}
        <line x1="40" x2="1160" y1="352" y2="352" stroke="rgba(30,27,75,0.10)" strokeWidth="0.8" />
        <circle cx="46" cy="376" r="5" fill={INK} />
        <text x="58" y="380" fontSize="10" fill={MUTED}>
          起點
        </text>
        <circle cx="118" cy="376" r="7" fill="none" stroke={INK} />
        <circle cx="118" cy="376" r="4" fill={INK} />
        <text x="130" y="380" fontSize="10" fill={MUTED}>
          終態
        </text>
        <path d="M 186 376 H 226" stroke={MUTED} strokeWidth="1.2" markerEnd="url(#rusmi-arw)" />
        <text x="234" y="380" fontSize="10" fill={MUTED}>
          合法轉換
        </text>
        <path d="M 322 376 H 362" stroke={ACCENT} strokeWidth="1.2" markerEnd="url(#rusmi-arw-ac)" />
        <text x="370" y="380" fontSize="10" fill={MUTED}>
          自留迴圈
        </text>
        <text x="450" y="380" fontSize="10" fill="#B91C1C">
          ✕
        </text>
        <text x="466" y="380" fontSize="10" fill={MUTED}>
          不存在的轉換（不畫線，另列於右側清單）
        </text>
      </svg>
    </div>
  );
}

function GuardPanel({ selection }: { selection: Selection }) {
  let content: ReactNode;

  if (selection === null) {
    content = (
      <p className="text-sm text-slate-600">
        核心洞察：爭議中不是終態，但它是唯一會停在原地的狀態——出口全部要人裁定，沒有一條自動路徑。
      </p>
    );
  } else if (selection.kind === 'transition') {
    const transition = TRANSITIONS.find((t) => t.id === selection.id) as (typeof TRANSITIONS)[number];
    const fromLabel = transition.from === null ? '起始' : STATE_LABELS[transition.from];
    content = (
      <div className="space-y-1">
        <p className="text-sm font-medium text-slate-800">
          {fromLabel} <ArrowRight size={12} className="inline" /> {STATE_LABELS[transition.to]}
        </p>
        <p className="text-sm text-slate-600">守衛條件：{transition.guard}</p>
        <p className="text-xs text-slate-400">{transition.clause}</p>
      </div>
    );
  } else {
    const nodeId = selection.id;
    const related = TRANSITIONS.filter(
      (t) => (t.from === null ? 'null' : t.from) === nodeId || t.to === nodeId
    );
    content = (
      <div className="space-y-2">
        <p className="text-sm font-medium text-slate-800">與「{STATE_LABELS[selection.id]}」相關的轉換</p>
        <div className="space-y-1">
          {related.map((t) => (
            <p key={t.id} className="text-sm text-slate-600">
              <span className="font-medium">
                {t.from === null ? '起始' : STATE_LABELS[t.from]} <ArrowRight size={11} className="inline" />{' '}
                {STATE_LABELS[t.to]}：
              </span>
              {t.guard}
              <span className="ml-1 text-xs text-slate-400">（{t.clause}）</span>
            </p>
          ))}
        </div>
      </div>
    );
  }

  return <div className="min-h-[92px] rounded-lg border border-slate-200 bg-white p-4">{content}</div>;
}

function ToggleButton({
  pressed,
  onToggle,
  labelOn,
  labelOff,
  disabled = false,
}: {
  pressed: boolean;
  onToggle: () => void;
  labelOn: string;
  labelOff: string;
  disabled?: boolean;
}) {
  return (
    <button
      type="button"
      aria-pressed={pressed}
      disabled={disabled}
      onClick={onToggle}
      className={clsx(
        'rounded-lg border px-3 py-1 text-sm font-medium transition-colors motion-reduce:transition-none disabled:cursor-not-allowed disabled:opacity-50',
        pressed ? 'border-emerald-500 bg-green-50 text-emerald-600' : 'border-slate-200 bg-white text-slate-500'
      )}
    >
      {pressed ? labelOn : labelOff}
    </button>
  );
}

function DecisionPicker({
  outKeyName,
  value,
  disabled,
  onChange,
}: {
  outKeyName: string;
  value: ReviewDecision;
  disabled: boolean;
  onChange: (decision: ReviewDecision) => void;
}) {
  const decisions: ReviewDecision[] = ['approve', 'modify', 'bypass'];
  return (
    <div>
      <p className="mb-1 text-sm text-slate-600">{outKeyName}</p>
      <div role="radiogroup" aria-label={`${outKeyName} 決策`} className="flex flex-wrap gap-2">
        {decisions.map((decision) => {
          const visual = DECISION_VISUALS[decision];
          const Icon = visual.icon;
          const isChecked = value === decision;
          return (
            <button
              key={decision}
              type="button"
              role="radio"
              aria-checked={isChecked}
              disabled={disabled}
              onClick={() => onChange(decision)}
              className={clsx(
                'flex items-center gap-1 rounded-lg border px-2 py-1 text-xs font-medium transition-colors motion-reduce:transition-none disabled:cursor-not-allowed disabled:opacity-50',
                isChecked ? 'border-indigo-500 bg-indigo-50 text-indigo-600' : 'border-slate-200 bg-white text-slate-500'
              )}
            >
              <Icon size={14} />
              {visual.label}
            </button>
          );
        })}
      </div>
    </div>
  );
}

function DerivedResultBanner({
  derivedStatus,
  clauseLabel,
}: {
  derivedStatus: ReviewUnitStatus | null;
  clauseLabel: string;
}) {
  const label = derivedStatus === null ? '不成立審核單位（null）' : STATE_LABELS[derivedStatus];
  const colorClass =
    derivedStatus === 'finalized'
      ? 'border-emerald-500 bg-green-50 text-emerald-600'
      : derivedStatus === 'disputed'
        ? 'border-yellow-200 bg-yellow-50 text-yellow-700'
        : 'border-slate-200 bg-white text-slate-500';

  return (
    <div className={clsx('rounded-lg border px-3 py-2 text-sm font-medium', colorClass)}>
      推導結果：{label}（依 {clauseLabel}）
    </div>
  );
}

function DecisionSimulator({
  sim,
  setSim,
  derivedStatus,
  clauseLabel,
}: {
  sim: SimState;
  setSim: Dispatch<SetStateAction<SimState>>;
  derivedStatus: ReviewUnitStatus | null;
  clauseLabel: string;
}) {
  const reviewerToggleDisabled = !sim.annotatorSubmitted;
  const outKeyControlsDisabled = !sim.annotatorSubmitted || !sim.reviewerSubmitted;

  const disputedOutKeys = (['outKeyA', 'outKeyB'] as const).filter(
    (key) => sim.outKeyDecisions[key] === 'modify' || sim.outKeyDecisions[key] === 'bypass'
  );

  return (
    <div className="space-y-4 rounded-lg border border-slate-200 bg-white p-4">
      <div>
        <p className="mb-1 text-sm font-medium text-slate-700">標記員已提交？</p>
        <ToggleButton
          pressed={sim.annotatorSubmitted}
          onToggle={() => setSim((s) => ({ ...s, annotatorSubmitted: !s.annotatorSubmitted }))}
          labelOn="是"
          labelOff="否"
        />
        {!sim.annotatorSubmitted && (
          <p className="mt-2 text-sm text-slate-500">
            不成立審核單位（null）——標記員尚未提交，其餘控制項暫不適用（FR-051 判定式第 1 句）。
          </p>
        )}
      </div>

      <div>
        <p className="mb-1 text-sm font-medium text-slate-700">審核員已提交？</p>
        <ToggleButton
          pressed={sim.reviewerSubmitted}
          onToggle={() => setSim((s) => ({ ...s, reviewerSubmitted: !s.reviewerSubmitted }))}
          labelOn="是"
          labelOff="否"
          disabled={reviewerToggleDisabled}
        />
        {sim.annotatorSubmitted && !sim.reviewerSubmitted && (
          <p className="mt-2 text-sm text-slate-500">狀態為待審（pending）——審核員尚未提交（FR-051 判定式第 2 句）。</p>
        )}
      </div>

      <div className={clsx('space-y-3', outKeyControlsDisabled && 'pointer-events-none opacity-50')}>
        <p className="text-xs text-slate-400">
          教學示意：此處固定示範 2 個 outKey，實際 outKey 數依任務 outputs[] 決定。
        </p>
        <DecisionPicker
          outKeyName="outKeyA"
          value={sim.outKeyDecisions.outKeyA}
          disabled={outKeyControlsDisabled}
          onChange={(decision) =>
            setSim((s) => ({ ...s, outKeyDecisions: { ...s.outKeyDecisions, outKeyA: decision } }))
          }
        />
        <DecisionPicker
          outKeyName="outKeyB"
          value={sim.outKeyDecisions.outKeyB}
          disabled={outKeyControlsDisabled}
          onChange={(decision) =>
            setSim((s) => ({ ...s, outKeyDecisions: { ...s.outKeyDecisions, outKeyB: decision } }))
          }
        />
      </div>

      {!outKeyControlsDisabled && disputedOutKeys.length > 0 && (
        <div className="space-y-2 rounded-lg border border-yellow-200 bg-yellow-50 p-3">
          <p className="flex items-center gap-1 text-xs font-medium text-yellow-700">
            <Scale size={14} /> 爭議項解決狀態
          </p>
          {disputedOutKeys.map((key) => (
            <div key={key} className="flex items-center justify-between gap-2">
              <span className="text-sm text-slate-600">{key}</span>
              <ToggleButton
                pressed={sim.disputedResolved[key]}
                onToggle={() =>
                  setSim((s) => ({
                    ...s,
                    disputedResolved: { ...s.disputedResolved, [key]: !s.disputedResolved[key] },
                  }))
                }
                labelOn="已仲裁或例外池收尾"
                labelOff="尚未解決"
              />
            </div>
          ))}
        </div>
      )}

      <DerivedResultBanner derivedStatus={derivedStatus} clauseLabel={clauseLabel} />
    </div>
  );
}

function NonexistentList({
  selectedId,
  onSelect,
}: {
  selectedId: NonexistentId | null;
  onSelect: (id: NonexistentId) => void;
}) {
  const selected = NONEXISTENT.find((item) => item.id === selectedId) ?? null;

  return (
    <div className="space-y-3 rounded-lg border border-red-200 bg-white p-4">
      <p className="flex items-center gap-1 text-sm font-medium text-red-700">
        <Ban size={14} /> 規格中明確不存在
      </p>
      <div className="space-y-1">
        {NONEXISTENT.map((item) => (
          <button
            key={item.id}
            type="button"
            onClick={() => onSelect(item.id)}
            className={clsx(
              'flex w-full items-center gap-2 rounded-lg border px-2 py-1.5 text-left text-xs transition-colors motion-reduce:transition-none',
              selectedId === item.id ? 'border-red-700 bg-red-50 text-red-700' : 'border-slate-200 bg-white text-slate-600'
            )}
          >
            <Ban size={14} className="shrink-0" />
            <span>{item.label}</span>
          </button>
        ))}
      </div>
      <div className="min-h-[72px] rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700">
        {selected ? selected.reason : '點選上方項目查看為何不存在。'}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// 根元件
// ---------------------------------------------------------------------------

export default function ReviewUnitStateMachineInteractive() {
  const [sim, setSim] = useState<SimState>({
    annotatorSubmitted: true,
    reviewerSubmitted: false,
    outKeyDecisions: { outKeyA: 'approve', outKeyB: 'approve' },
    disputedResolved: { outKeyA: false, outKeyB: false },
  });
  const [selection, setSelection] = useState<Selection>(null);
  const [selectedNonexistentId, setSelectedNonexistentId] = useState<NonexistentId | null>(null);

  const derivedStatus = useMemo(() => deriveReviewUnitStatus(sim), [sim]);
  const clauseLabel = useMemo(() => deriveClauseLabel(sim), [sim]);
  const pathEdges = useMemo(() => derivePathEdges(sim), [sim]);

  return (
    <div className="rusm-root not-prose space-y-6">
      <style dangerouslySetInnerHTML={{ __html: SCOPED_CSS }} />
      <StateDiagram
        derivedStatus={derivedStatus}
        pathEdges={pathEdges}
        selection={selection}
        onSelect={setSelection}
      />
      <GuardPanel selection={selection} />
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-[1fr_320px]">
        <DecisionSimulator sim={sim} setSim={setSim} derivedStatus={derivedStatus} clauseLabel={clauseLabel} />
        <NonexistentList selectedId={selectedNonexistentId} onSelect={setSelectedNonexistentId} />
      </div>
    </div>
  );
}
