blank_issues_enabled: false
contact_links:
  - name: "Discord 聊天室"
    url: "https://discord.com/"
    about: "有任何問題請在DC回報，我們會盡快回覆你！"

  - name: "後台入口"
    url: "https://XXXXXX/login"
    about: "帳號密碼請找PM索取"

  - name: "前台首頁"
    url: "https://XXXXXXX.com/"
    about: "帳號密碼請找PM索取"
