classes: {
  base: {
    style: {
      bold: true
      font-size: 24
    }
  }

  person: {
    shape: person
  }

  animated: {
    style: {
      animated: true
    }
  }

  multiple: {
    style: {
      multiple: true
    }
  }

  tool: {
    style: {
      bold: true
      font-size: 22
      fill: PapayaWhip
      fill-pattern: grain
      border-radius: 8
    }
  }

  module: {
    style: {
      bold: true
      font-size: 22
      fill: honeydew
      fill-pattern: grain
      border-radius: 8
    }
  }

  highlight: {
    style: {
      bold: true
      font-size: 22
      fill: LightCyan
      fill-pattern: grain
      border-radius: 8
    }
  }

  warning: {
    shape: diamond
    style: {
      bold: true
      font-size: 20
      fill: MistyRose
    }
  }

  step: {
    shape: step
    style: {
      bold: true
      font-size: 20
    }
  }

  store: {
    shape: cylinder
    style: {
      bold: true
      font-size: 22
      font: mono
    }
  }
}
